### ISSUE TITLE
Incremental Streaming vs Culimative Streaming

### ISSUE THREAD

**Issue by jxnl** [anthropics/anthropic-sdk-python#10]
I noticed that Anthropics APIs use cumulative streaming in the completion endpoint, resulting in repetitive data being sent over the wire. Is there a reason for this design choice? I imagine Incremental streaming is typically preferred for efficiency.

I see this is on the endpoint and not a python or ts issue. so this could impact existing customers.

**Comment by mikelambert** [comment]
Thanks, this is something we're planning to improve in the next incarnation of our API.

**Comment by nt92** [comment]
+1 to this!

**Comment by jxnl** [comment]
@mikelambert do you know what the priority is for this? I saw the 100k announcement and i think it'd be even more needed if i generate a response that is 50k tokens. The stream would over a billion tokens over the wire. (sum 1 to 50k)

**Comment by jenan-ant** [comment]
@jxnl Coming soon!

**Comment by jxnl** [comment]
Awesome! 100k is going to be wild congrats on the announcement

**Comment by jenan-ant** [comment]
The new version of the SDK and API support incremental streaming!
