### ISSUE TITLE
Docs typo: throughout should be throughput

### ISSUE THREAD

**Issue by tomviner** [anthropics/anthropic-sdk-python#105]
On https://docs.anthropic.com/claude/reference/selecting-a-model
> Claude Instant: low-latency, high throughout

should be _throughput_.

As detected by Claude:
<img width="678" alt="image" src="https://github.com/anthropics/anthropic-sdk-python/assets/167319/ec5704f8-20fc-442a-8805-25af8947810f">

**Comment by rattrayalex** [comment]
Thanks @tomviner , we'll get this fixed shortly!

**Comment by jenan-ant** [comment]
(done, thanks!)
