### ISSUE TITLE
Prompt formatting inconsistencies between python sdk and API docs

### ISSUE THREAD

**Issue by lucasgadams** [anthropics/anthropic-sdk-python#106]
In the examples give in the python sdk, there is a space between the end of the user message and the beginning of AI_PROMPT, whereas in the official API docs, there is specifically no space: https://docs.anthropic.com/claude/reference/getting-started-with-the-api#prompt-formatting. While this seems minor we know that LLMs can have varied outputs depending on small changes to things like this. What is the recommended way to do it?

**Comment by rattrayalex** [comment]
Follow the official docs; the space is not required. We include them here for readability, but you're likely correct we should remove them.

**Comment by lucasgadams** [comment]
Thanks! Stainless is dope btw :)

**Comment by rattrayalex** [comment]
😄 thank you!

This fix is in our merge queue and should be released before long. Thanks for reporting!
