### ISSUE TITLE
Docs Issue: import AsyncAnthropic missing

### ISSUE THREAD

**Issue by aymansyam** [anthropics/anthropic-sdk-python#107]
In the README where it mentions about AsyncAnthropic, the import statement is using Anthropic instead of AsyncAnthropic

> Async Usage

> Simply import AsyncAnthropic instead of Anthropic and use await with each API call:

```
from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT

anthropic = AsyncAnthropic(
    # defaults to os.environ.get("ANTHROPIC_API_KEY")
    api_key="my api key",
)
```

**Comment by rattrayalex** [comment]
Thanks for reporting, we'll get this fixed soon!
