### ISSUE TITLE
Support Pydantic >= 2.0.0 ?

### ISSUE THREAD

**Issue by zbitouzakaria** [anthropics/anthropic-sdk-python#115]
Hello,

I noticed that the project is currently depending on pydantic version "^1.9.0". Given that pydantic is already at 2.1.1, I was wondering if there are any plans to upgrade your dependencies for this project.

Thanks!

**Comment by rattrayalex** [comment]
Work on this is underway! I _expect_ it to be released next week, but we can't yet promise anything.

**Comment by tomviner** [comment]
Excellent. I'll stop vedorizing anthropic in llm-claude once this is
released

**Comment by RobertCraigie** [comment]
Support for Pydantic v2 will be added in the next release!

**Comment by RobertCraigie** [comment]
This has been released in v0.3.10!

**Comment by zbitouzakaria** [comment]
Yaaay big thanks !
