### ISSUE TITLE
Problem with the billing account that is used to host the tokenizer.

### ISSUE THREAD

**Issue by mobarski** [anthropics/anthropic-sdk-python#14]
The simplest possible use of count_tokens ends with an error
```python
import anthropic
anthropic.count_tokens('hello')
```

The error:
```
raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mobarski/.local/lib/python3.10/site-packages/anthropic/tokenizer.py", line 34, in count_tokens
    tokenizer = get_tokenizer()
  File "/home/mobarski/.local/lib/python3.10/site-packages/anthropic/tokenizer.py", line 29, in get_tokenizer
    claude_tokenizer = Tokenizer.from_str(tokenizer_data)
Exception: expected value at line 1 column 1
```

A quick inspection in `tokenizer.py` shows the URL from where the tokenizer should be downloaded:
```
CLAUDE_TOKENIZER_REMOTE_FILE = "https://public-json-tokenization-0d8763e8-0d7e-441b-a1e2-1c73b8e79dc3.storage.googleapis.com/claude-v1-tokenization.json"
```

And trying to access this link in the browser gives this:
```html
<Error>
  <Code>UserProjectAccountProblem</Code>
  <Message>
    The project to be billed is associated with a closed billing account.
  </Message>
  <Details>
    The billing account for the owning project is disabled in state closed
  </Details>
</Error>
```

**Comment by mobarski** [comment]
The impact of this problem seems to be larger - completion endpoint is also affected!

Workaround:
`pip3 install anthropic==0.2.3`

**Comment by mikelambert** [comment]
Thank you for reporting, and sorry about this bug with the release that went out a few days ago. The bucket should be fixed as of earlier this afternoon (within a couple hours of this being posted). And https://github.com/anthropics/anthropic-sdk-python/pull/16 should make this additional check fail-open, so it shouldn't recur even if something happens to the bucket.
