### ISSUE TITLE
Async Calls Support

### ISSUE THREAD

**Issue by kevinlu1248** [anthropics/anthropic-sdk-python#15]
Hey there, I was wondering if asynchronous calls are or will be supported. Thanks!

**Comment by mikelambert** [comment]
I believe this got added [a few days ago](https://github.com/anthropics/anthropic-sdk-python/blob/main/anthropic/api.py#L243-L256), though I am hoping to make a marginal improvement in https://github.com/anthropics/anthropic-sdk-python/pull/17

**Comment by mikelambert** [comment]
v0.2.6 should support async now
