### ISSUE TITLE
Upgrade to pydantic 2.0

### ISSUE THREAD

**Issue by aravindsrinivasan** [anthropics/anthropic-sdk-python#165]
Pydantic 2 has been out for a while but I'm unable to use it in any project that has an anthropic dependency because of this library's versioning restrictions: `pydantic [required: >=1.9.0,<2.0.0, installed: 1.9.0]`. Could we upgrade it?

**Comment by rattrayalex** [comment]
Good news, we added support for Pydantic 2 in [v0.3.10](https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.3.10)! Let me know if you run into any issues after upgrading to the latest version of this library.
