### ISSUE TITLE
Docs feature suggestion

### ISSUE THREAD

**Issue by ericciarla** [anthropics/anthropic-sdk-python#179]
Hi there,

I have been a huge fan and user of Anthropic/Claude for a while now! When I was implementing Claude using the SDK + docs I thought it would be awesome to have a Mendable AI companion integrated on the docs site. I ended up ingesting part of your docs site and building a demo both for my own use and to show you guys: [https://www.mendable.ai/demos/anthropic](https://www.mendable.ai/demos/anthropic)

This can help devs implement faster while also giving you the data you need to improve the docs and get some visibility on what users are asking and wondering about. 

Please let me know any changes, or suggestions that you might have. It would be super awesome to implement with you all.

Hopefully, you like it!

A bit more background: I am one of the co-founders of Mendable.ai. We have done tens of thousands of messages with Claude and have implemented similar AI companions with Langchain, Snapchat, Llama Index. Would love to work with Anthropic as well :)

**Comment by rattrayalex** [comment]
Thanks for dropping a line, @ericciarla ! I've passed your message along; someone from the Anthropic team will reach out if there's interest.

**Comment by ericciarla** [comment]
Awesome, thank you @rattrayalex
