### ISSUE TITLE
SyncClient catching base level exception in _request

### ISSUE THREAD

**Issue by insiderscore-jeff** [anthropics/anthropic-sdk-python#184]
Ran into an issue, where SyncClient (and Async) is catching Exception (python base exception) in _request() and then doing a retry.   I ran square into this with a SIGTERM handler which raises a Python exception so code can clean up and exit cleanly when terminated (ie running in a managed container) and nothing actually happening.

Code in lib is in _base_client.py around like 913 and also 1322

```python
import signal
import os
import time
import anthropic
from anthropic import Anthropic

class SIGTERMException(Exception):
    """
    used to indicate our failure was sigterm received
    """
    pass

def sigtermHandler(signal, frame):
    print("Got sigterm")
    raise SIGTERMException("sigterm")

signal.signal(signal.SIGTERM, sigtermHandler)
print("PID: %d" % os.getpid())
time.sleep(5)

print("Starting, kill process in another window")

client = Anthropic()
try:
    res = client.completions.create(
        model = "claude-2",
        prompt = f"{anthropic.HUMAN_PROMPT} how does a court case get to the supreme court? {anthropic.AI_PROMPT}", 
        max_tokens_to_sample = 1500
    )
except SIGTERMException:
    print("Main got sigterm")
    exit(0)
except Exception as e:
    print("Generic exception", e)
    exit(-1)

print("Done: %s", res.completion)

```

If you run this, and then kill the pid from another terminal after it starts the Anthropic request, you'll see the sigterm handler fire, but the exception is not passed up.

```
PID: 801977
Starting, kill process in another window
Got sigterm
Done: %s  Here is a brief overview of how a court case reaches the U.S. Supreme Court:

```

Thanks.

**Comment by rattrayalex** [comment]
Thank you for reporting this! We shouldn't be swallowing those sorts of exceptions, we'll get right on it.

**Comment by rattrayalex** [comment]
Ah, it looks like this is happening because you're using a custom sigterm handler with a custom Exception class which inherits from `Exception` instead of `BaseException`. 

To raise your own exception like this that avoids libraries' `except Exception` code (which is a common pattern in many libraries), your custom class should inherit from `BaseException` instead, like so:


```py
class SIGTERMException(BaseException):
    """
    used to indicate our failure was sigterm received
    """
    pass
```

Does that make sense?

**Comment by insiderscore-jeff** [comment]
Gotcha - thanks!
