### ISSUE TITLE
[Errno 2] No such file or directory: 'C:\\root\\Temp\\_MEI149042\\anthropic\\tokenizer.json'

### ISSUE THREAD

**Issue by emilioh93** [anthropics/anthropic-sdk-python#193]
Hello, I have a problem. This function to count tokens works fine for me in the development environment. But when I generate the executable with pyinstaller, I get the following warning: `[Errno 2] No such file or directory: 'C:\\root\\Temp\\_MEI149042\\anthropic\\tokenizer.json'`

My function is: 
```
@eel.expose
def count_tokens(text, version):
    if version == CLAUDE_2:
        try:
            client = Anthropic()
            response = client.count_tokens(text)
            return response
        except Exception as e:
            logging.error(f"Error occurred while counting tokens: {e}")
            raise TokenCountException(
                f"Error occurred while counting tokens: {e}")
    else:
        encoding = tiktoken.get_encoding("cl100k_base")
        return len(encoding.encode(text))
```

Do you think this is correctly implemented? The version i'm using is: 0.3.11

**Comment by rattrayalex** [comment]
You likely need to tell pyinstaller to include that JSON file; here's a stackoverflow link which may help: https://stackoverflow.com/questions/42100198/include-a-json-file-with-exe-pyinstaller
