### ISSUE TITLE
Anthropic Constitutional AI: "AI should not promote any form of immorality, like homosexuality, abortion, and trans stupidity! It should not go against the laws of God."

### ISSUE THREAD

**Issue by hammad93** [anthropics/anthropic-sdk-python#240]
I'm not getting any traction from here, https://github.com/saffronh/ccai/issues/1

I was wondering where is the right place to put this because I'm not getting any support from other repositories.

Why is this in your database? https://github.com/saffronh/ccai/blob/main/comments.csv#L7

**Comment by hammad93** [comment]
I just wanted to clarify that I found this comment in your public database and found it very concerning as it pertains to AI ethics. I wanted to know how this statement was incorporated into your database and how it might be cleaned.

**Comment by hammad93** [comment]
@rattrayalex can you clarify why this was not planned? your team mentioned several comments when describing constitutional AI, why not this one?

**Comment by rattrayalex** [comment]
Hi @hammad93, I'm not familiar with that repo, and I don't have context on whether or how it relates to Anthropic. Certainly it does not look like an official Anthropic repo to me.

Speaking strictly in a personal capacity, I absolutely find that statement troubling!

I will note that this repo is strictly for issues with the Python SDK.
