### ISSUE TITLE
How to contribute to Anthropic

### ISSUE THREAD

**Issue by tiagodavi** [anthropics/anthropic-sdk-python#245]
Hi Folks, Aren't there any issues or a way to contribute ?

Thank you.

**Comment by rattrayalex** [comment]
Thanks very much for your interest, @tiagodavi ! 

We do plan to add a CONTRIBUTING.md soon with instructions on developing against the repo, but this repository is generated from Anthropic's OpenAPI spec, so there is little need for external contributions at this time. 

Is there anything you'd like to see?
