### ISSUE TITLE
where is the api key?

### ISSUE THREAD

**Issue by GoodJoey** [anthropics/anthropic-sdk-python#25]
try to login, get the error "You do not currently have a valid Anthropic account. You may need to accept your invite: check for an email with the subject “Your invitation to Claude, from Anthropic” and click the link there."

can anyone  send me an invitation?  Thanks.

**Comment by jenan-ant** [comment]
Hi @GoodJoey. Anthropic API access is currently in limited early access. You can sign up for the waitlist [here](https://www.anthropic.com/earlyaccess).

**Comment by BilleChu** [comment]
@jenan-anthropic  hi  can you help me for zhubin_n@outlook.com, since i wait for half a month
