### ISSUE TITLE
Anthropic import error

### ISSUE THREAD

**Issue by sungbin07** [anthropics/anthropic-sdk-python#250]
I'm trying to use the example code in the ReadME file, but I get the following error:

```
    from anthropic import AsyncAnthropic, HUMAN_PROMPT, AI_PROMPT
ImportError: cannot import name 'AsyncAnthropic' from partially initialized module 'anthropic' (most likely due to a circular import) 
```

I downloaded the latest version 0.7.3.

**Comment by rattrayalex** [comment]
What is the filename you're calling it from? If it's `anthropic.py`, `json.py`, or similar, you may encounter this issue.

**Comment by rattrayalex** [comment]
If you're still having problems, please provide a repo that reproduces the issue.

**Comment by collindutter** [comment]
I ran into a similar issue, I was running from a file called `tokenizers.py` which caused a circular import [here](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/_client.py#L11). Renaming as @rattrayalex suggested resolved it 🥳
