### ISSUE TITLE
Model defaults to version 2.1 even when specified to claude-2

### ISSUE THREAD

**Issue by krasaee** [anthropics/anthropic-sdk-python#255]
Hello and thank you for providing access to the SDK and Claude APIs. 

Two notes:

**1. Pydantic Versioning:**
The Anthropics SDK currently has a hard dependency on Pydantic version 1.0, which causes other modules, of which are dependent on higher versions, to break.

**2. Model Versioning in Completion API:**
 When using the Python SDK's completion API, it appears that the specified model version is not being honored. Despite selecting "claude-2" as the model, the API defaults to version 2.1. 
 
 Below are the relevant version details and execution code:

**Version Information:**

```
% conda list | grep anthropic
anthropic 0.7.4 pyhd8ed1ab_0 conda-forge
```

**Execution Code:**

```
completion = self.anthropic.completions.create(
    model="claude-2",
    max_tokens_to_sample=4096,
    prompt=final_prompt,
)
```

**Response:**
```
completion.model
'claude-2.1'
```

**Comment by rattrayalex** [comment]
Pydantic 2 is suppoted now - what have you the impression it wasn't?

Claude-2 is now an alias for Claude-2.1

**Comment by krasaee** [comment]
Thank you for your response and reaching out to us.

We are also interested in testing Claude-2.0. We've noticed that Claude-2.1 demonstrates different responses, particularly on controversial topics such as nonhuman animal beings. While these differences are truly appreciated, we would also like to evaluate Claude-2.0. 

Is there a way to access and test this specific version? if not, we understand.

Apropos of  Pydantic 2.0, we suspect there might be an issue with its compatibility on ARM versions. Could this be the case? see below. (perhaps the channel order needs to be changed or a new package channel is required?)

```
(alethic-processor) % conda install anthropic
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
 - pytorch-nightly
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/kasrarasaee/miniconda3/envs/alethic-processor

  added / updated specs:
    - anthropic


The following NEW packages will be INSTALLED:

  anthropic          conda-forge/noarch::anthropic-0.7.4-pyhd8ed1ab_0 
  anyio              conda-forge/noarch::anyio-3.7.1-pyhd8ed1ab_0 
  distro             conda-forge/noarch::distro-1.8.0-pyhd8ed1ab_0 
  exceptiongroup     conda-forge/noarch::exceptiongroup-1.2.0-pyhd8ed1ab_0 
  h11                conda-forge/noarch::h11-0.14.0-pyhd8ed1ab_0 
  h2                 conda-forge/noarch::h2-4.1.0-pyhd8ed1ab_0 
  hpack              conda-forge/noarch::hpack-4.0.0-pyh9f0ad1d_0 
  httpcore           conda-forge/noarch::httpcore-1.0.2-pyhd8ed1ab_0 
  httpx              conda-forge/noarch::httpx-0.25.1-pyhd8ed1ab_0 
  hyperframe         conda-forge/noarch::hyperframe-6.0.1-pyhd8ed1ab_0 
  sniffio            conda-forge/noarch::sniffio-1.3.0-pyhd8ed1ab_0 

The following packages will be SUPERSEDED by a higher-priority channel:

  pydantic           conda-forge/noarch::pydantic-2.5.2-py~ --> conda-forge/osx-arm64::pydantic-1.10.13-py311h05b510d_1 


Proceed ([y]/n)? 

```


**FORCE FIX**
```
# (alethic-processor) % conda uninstall pydantic --force-remove
# (alethic-processor) % conda install pydantic --no-deps

# (alethic-processor) % conda list | egrep "anthropic|pydantic"
anthropic                 0.7.4              pyhd8ed1ab_0    conda-forge
pydantic                  2.5.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.14.5          py311h94f323b_0    conda-forge

```

**Comment by rattrayalex** [comment]
1. Have you tried passing `model='claude-2.0'`?
2. Perhaps Pydantic 2 doesn't have ARM binaries available on Anaconda? You may need to request them. Some relevant links I found:
    - https://anaconda.org/conda-forge/pydantic
    - https://github.com/pydantic/pydantic/discussions/4699

**Comment by krasaee** [comment]
It turns out specifying "model='claude-2.0'" does indeed stick to version 2.0, while "claude-2" gets the latest version of the claude-2 model. Thanks for pointing that out.

With respect to pydantic 2 and arm arch, using the noarch version with a forced installation works well (as mentioned above). At some point, 'when' I run into more issues, I will look into the dependency resolution issue with arm.

Thanks for the support.

Respectfully,

- Kas

**Comment by rattrayalex** [comment]
My pleasure!

I'd appreciate it if you could open an issue on the pydantic project suggesting that they have explicit Linux ARM support, and sharing your experience and workaround.
