### ISSUE TITLE
Is there a method/endpoint for validating an API key? 

### ISSUE THREAD

**Issue by felix3peng** [anthropics/anthropic-sdk-python#268]
Hello, I'm wondering if there's a built-in method for validating an API key using either the API or the python SDK. From what I can tell after going through the docs and the code for the Anthropic client, there isn't a clear way to do this besides sending a test request.

Ideally, this method would test whether an API key is valid or not without having to use tokens by sending a test request to the completions endpoint.

Would appreciate any support or clarification on why this would not be supported! Thank you.

**Comment by rattrayalex** [comment]
No, you will need to make a request. To limit the tokens consumed, you might try setting `max_tokens_to_sample=1` or so.
