### ISSUE TITLE
Anthropic's dependent library "Anyio" is incompatible with Gunicorn worker class "Eventlet" or "gevent"

### ISSUE THREAD

**Issue by abhishekmunjal** [anthropics/anthropic-sdk-python#281]
I have a python application running using eventlet for serving requests.
I also need to install anthropic, but it never settles with the application because of this async library "Anyio".

Can't anthropic work without "Anyio" ? We can externally provide the asynchronous feature right ?

**Comment by abhishekmunjal** [comment]
> I have a python application running using eventlet for serving requests. I also need to install anthropic, but it never settles with the application because of this async library "Anyio".
> 
> Can't anthropic work without "Anyio" ? We can externally provide the asynchronous feature right ?

I made it work by downgrading "AnyIO" to 3.7.0
But now it creates another issue, it doesn't work with Celery now.
Tried different versions but no luck.

**Comment by rattrayalex** [comment]
What issues are you running into when installing `anyio` alongside `gevent`/`Eventlet`? Can you share the specific library versions of all relevant libraries, the code you're using, and the errors/behavior you're seeing?

cc @robertcraigie

**Comment by abhishekmunjal** [comment]
> What issues are you running into when installing `anyio` alongside `gevent`/`Eventlet`? Can you share the specific library versions of all relevant libraries, the code you're using, and the errors/behavior you're seeing?
> 
> cc @RobertCraigie

So, as I mentioned the error that I got was resolved when I changed anyIO version to 3.7.0
the issue appears with trio
Eventlet latest version,
anyio latest version
this is an open issue mentioned here: https://github.com/eventlet/eventlet/issues/805


But, now I am getting a weird problem.
That, when anyIO is installed, I am not able to use celery.
Celery just doesn't accepts any task, doesn't even give any error, so I am not able to find out the problem as well.

**Comment by rattrayalex** [comment]
I'm sorry you're experiencing this issue! Subdependency problems like this are the worst. 

Unfortunately, we won't be able to remove this dependency. 

I suggest engaging more on the thread you linked. It seems that import order may help, and that httpcore (another subdependency of ours) may also be worth pinning.
