### ISSUE TITLE
Conversation with Claude

### ISSUE THREAD

**Issue by bobe94** [anthropics/anthropic-sdk-python#29]
First thing: I'm quite noob in Python.
I'm trying out this package, but I can't find a way to make a conversation longer than one sentence with Claude: how can I code an iterative conversation with him? Like "How are you?" "Not so well" "Why not?" "Because I'm tired". 

This is my code:

```python import anthropic
import os

c = anthropic.Client(api_key="XXX")

def ask_Claude(frase):
    resp = c.completion(
        prompt=f"{anthropic.HUMAN_PROMPT} {frase} {anthropic.AI_PROMPT}",
        stop_sequences=[anthropic.HUMAN_PROMPT],
        model="claude-v1.3",
        max_tokens_to_sample=3000,
    )
    print(resp)

ask_Claude("Am I dumb?")
ask_Claude("Did I ask you something before?") ```

**Comment by mikelambert** [comment]
When you prompt it with "Human: Question AI:", and it gives you "Answer", you can concatenate those two "Human: Question AI: Answer Human: Question2 AI:" and send it back to the model. (I'm paraphrasing for speed, please ensure you follow the proper formatting as detailed in https://console.anthropic.com/docs/prompt-design)
