### ISSUE TITLE
Getting incomplete responses in async mode

### ISSUE THREAD

**Issue by rc19** [anthropics/anthropic-sdk-python#295]
Hello I am using llama-index (v0.9.16) and using their async streaming apis (`achat_stream`) with their [simple chat engine](https://github.com/run-llama/llama_index/blob/ce75aa5d026524d9b36709769ea3f2e203ac5269/llama_index/chat_engine/simple.py#L141). 

However it seems like when I use openai sdk (for anyscale and open models), I get full responses while if I use anthropic sdk (for claude) I get the error 
```
<asyncio.locks.Event object at 0x13de7fe50 [unset]> is bound to a different event loop
```

I am confused as to if this is because of llama index or anthropic (given the same code works with openai call)

Any pointers?

**Comment by rattrayalex** [comment]
Can you share your sample code and a traceback?

**Comment by rc19** [comment]
```
from llama_index.llms import Anthropic, OpenAI
from llama_index import ServiceContext
from llama_index.chat_engine import SimpleChatEngine


# llm = OpenAI(
#                model=model,
  #              temperature=temperature,
    #            max_tokens=max_tokens,
      #          api_key=api_key,
        #        api_base=base_url,
          #      reuse_client=False,
            #    timeout=timeout,
           # )
llm = Anthropic(
                model=model,
                temperature=temperature,
                api_key=api_key,
                max_tokens=max_tokens,
                base_url=base_url,
                timeout=timeout,
            )
            
service_context = ServiceContext.from_defaults(
        llm=llm,
    )
ce = SimpleChatEngine.from_defaults(service_context=service_context)
response = await ce.astream_chat(user_message, chat_history)

async for message in response.async_response_gen():
     # do something
```

llama-iindex == 0.9.16
anthropic == 0.7.8
openai == 1.3.8

If I use openai, the above code works fine but with anthropic it shows
```WARNING::llama_index.chat_engine.types::Encountered exception writing response to history: <asyncio.locks.Event object at 0x13ad191d0 [unset]> is bound to a different event loop```

**Comment by rattrayalex** [comment]
Got it. This sounds like an issue with the llama_index library so I recommend you file an issue there.
