### ISSUE TITLE
What models is tokenizer used for?

### ISSUE THREAD

**Issue by jeremy-apollo** [anthropics/anthropic-sdk-python#305]
Hi there, i was wondering, whether the tokenizer provided in the sdk is used for all currently public models i.e. claude 2.1 and "claude-instant-1.2"? 

I'm assuming yes, but just wanted to double check this.

**Comment by x5a** [comment]
Hi @jeremy-apollo this is currently true, yes.

**Comment by jeremy-apollo** [comment]
thanks so much, for the quick answer :)
