### ISSUE TITLE
Claude claude-v1-100k showing 10k token limit

### ISSUE THREAD

**Issue by rlancemartin** [anthropics/anthropic-sdk-python#32]
I have API access and am testing `claude-v1-100k`.

I call API passing in `text` to the prompt, which is a large doc.

```
response = client.completion_stream(
    prompt=f"{anthropic.HUMAN_PROMPT} What are the limitations of task-specific fine-tuning? Use this context to answer: %s {anthropic.AI_PROMPT}"%text,
    stop_sequences=[anthropic.HUMAN_PROMPT],
    max_tokens_to_sample=200,
    model="claude-v1-100k",
    stream=True,)
for data in response:
    print(data)
```
 
I see max token count ~10k:  

```
ApiException: Prompt tokens (62386) + max-sampled tokens (200) exceeds max (9216)
```

Is it possible that some users do not have access to `claude-v1-100k`?

I also tried with a second API key.

**Comment by hwchase17** [comment]
i think this is just caused by being on old version of sdk

**Comment by rlancemartin** [comment]
Confirmed! 

Needs an update: `pip install anthropic --upgrade`

May be helpful for Anthropic to add to their docs (or I missed it)?
https://www.anthropic.com/index/100k-context-windows
https://console.anthropic.com/docs/api/reference#python

Older sdk appears to still accept the `100k` version name (`claude-v1-100k`), which is a bit confusing.

If it had thrown an error related to sdk compatibility, I would have upgraded immediately.

**Comment by jenan-ant** [comment]
@rlancemartin I'm glad this was resolved!

The validation error was in the older SDK, so there wouldn't be a way to mention SDK compatibility in the error message.

**Comment by rlancemartin** [comment]
> The validation error was in the older SDK, so there wouldn't be a way to mention SDK compatibility in the error message.

Thanks! Ya, not a big deal. 

It's just interesting that the older SDK accepted the new model version name `claude-v1-100k` without error.

Perhaps it simply defaults back to using `claude` if an invalid model name is entered.
