### ISSUE TITLE
`get_tokenizer` is thread-hostile

### ISSUE THREAD

**Issue by yifanmai** [anthropics/anthropic-sdk-python#33]
Race conditions during file modification between multiple calls to `get_tokenizer` can result in error such as `anthropic.tokenizer.TokenizerException: Failed to load tokenizer: EOF while parsing a value at line 1 column 0`.

`get_tokenizer` is thread-hostile. It should either have a docstring indicating that it's thread-hostile, or a lock should be used to make it thread-safe.

**Comment by jenan-ant** [comment]
The new version of the SDK includes the tokenizer in the repo, and uses `lru_cache`, which should be thread-safe. Please take a look!

**Comment by yifanmai** [comment]
Great, thanks for your help!
