### ISSUE TITLE
"{" "}" is not being able to include in prompt in both api and web requests 

### ISSUE THREAD

**Issue by deter3** [anthropics/anthropic-sdk-python#35]
When I put a json file as example in prompt ,  the api request is not going through due to KeyError , I guess the prompt treat { } as a system prompt .  can you advise the solution ?  below is the json file I put into prompt . 

`[
    {
     
        "verified": "yes",
        "relationship": "friends",
        "name": "John"
    },
    {
       
        "verified": "yes",
        "relationship": "workmates",
        "name": "Richard"
    }`

**Comment by mikelambert** [comment]
Can you share your python code that's failing, as well as the actual stacktrace/keyerror? Are you sticking the json in directly as the prompt, or doing `json.dumps()` first?

**Comment by deter3** [comment]
> Can you share your python code that's failing, as well as the actual stacktrace/keyerror? Are you sticking the json in directly as the prompt, or doing `json.dumps()` first?

I  stick the json into the prompt as the example of the result I want . I found out as long as there's { or  } inside prompt , there's the problem .

**Comment by rattrayalex** [comment]
This should be fixed in v0.3.0, which was just released; please let us know if the issue persists (and include a full repro script if you can).
