### ISSUE TITLE
Count Tokens for Bedrock

### ISSUE THREAD

**Issue by 14gaurav16** [anthropics/anthropic-sdk-python#353]
I am getting following when I am trying to calculate tokens in bedrock.

AttributeError: 'AnthropicBedrock' object has no attribute 'count_tokens'

It seems like there is no implementation for it.

Thanks.

**Comment by rattrayalex** [comment]
That's right; we're now deprecating token-counting in the client because the tokenization algorithms in Claude 3 are different (see deprecation notes on the count_tokens() method). The new recommendation is to look at usage in the return value.

**Comment by Smuglix** [comment]
@rattrayalex will there be a way to calculate how much tokens a given text takes without making a chat completion call?

**Comment by rattrayalex** [comment]
Not at this time, unfortunately. You can continue to use `count_tokens()` or other third-party libraries as a rough estimate for the time being. A better solution may be added in the future.

**Comment by opyate** [comment]
> or other third-party libraries as a rough estimate

Thanks for the suggestion.

Would you recommend `tiktoken` (and if so, `cl100k_base`?), `sentencepiece`, or the [rough heuristic as per OpenAI](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)?

I.e. 

> 1 token ~= 4 chars in English
> 1 token ~= ¾ words
> 100 tokens ~= 75 words

**Comment by rattrayalex** [comment]
@x5a might be better positioned to answer that.
