### ISSUE TITLE
Endpoint to get all models

### ISSUE THREAD

**Issue by anjor** [anthropics/anthropic-sdk-python#361]
Would it be possible to add an endpoint to get all models served via the Anthropic API?

**Comment by jenan-ant** [comment]
Hi @anjor, thanks for the feature request! We're always considering features like this and may end up building it in the future.  In the meantime, the SDKs should have type hints for model names, and we generally keep those up to date.

Note that we only track Python SDK-specific issues in this repository, so I'm going to close this issue.
