### ISSUE TITLE
unable to install anthropic[bedrock]

### ISSUE THREAD

**Issue by sunnygoel87** [anthropics/anthropic-sdk-python#369]
Hi Team,

while trying to install the `anthropic[bedrock]` package on my machine, I'm getting the following error. Am I doing anything wrong?

```
pip3 install -U anthropic[bedrock]
zsh: no matches found: anthropic[bedrock]
```

**Comment by rattrayalex** [comment]
You may need to quote it:

```
pip3 install 'anthropic[bedrock]'
```

**Comment by sunnygoel87** [comment]
Thanks for your response, @rattrayalex . That worked. I'm assuing, we need to mention this within quotes in `requirements.txt` file as well, correct ?

**Comment by rattrayalex** [comment]
I don't believe so - the quoting is just needed for zsh, which otherwise interprets the brackets differently from what we intend.
