### ISSUE TITLE
Model Claude 3 Haiku is not available ?

### ISSUE THREAD

**Issue by jonaskahn** [anthropics/anthropic-sdk-python#370]
I tried to contact with supporters, but I can not find them out. 
Could developers tell me when Claude 3 haiku model is available? I tried with console playground but no model 3 haiku.
Thanks

**Comment by bigEvilBanana** [comment]
According to documentation haiku is not available for api yet. 

Here's a list of supported models https://docs.anthropic.com/claude/docs/models-overview#model-comparison

**Comment by justinvf** [comment]
As mentioned in the article, Haiku is coming soon! The launch will be announced on [Twitter](https://twitter.com/AnthropicAI) and [LinkedIn](https://www.linkedin.com/company/anthropicresearch). I'll update this issue as well.

**Comment by justinvf** [comment]
[Launched!](https://www.anthropic.com/news/claude-3-haiku)

**Comment by jonaskahn** [comment]
Amazinggggg 🥰🥰🥰🥰
