### ISSUE TITLE
Update count_tokens() to be accurate for the Claude 3 series of models

### ISSUE THREAD

**Issue by rbehal** [anthropics/anthropic-sdk-python#375]
- Plenty of apps, including [ourselves](https://agenthub.dev/), validate token counts before sending requests to the API to proactively handle errors

```
    def count_tokens(
        self,
        text: str,
    ) -> int:
        """Count the number of tokens in a given string.

        Note that this is only accurate for older models, e.g. `claude-2.1`. For newer
        models this can only be used as a _very_ rough estimate, instead you should rely
        on the `usage` property in the response for exact counts.
        """
        # Note: tokenizer is untyped
        tokenizer = self.get_tokenizer()
        encoded_text = tokenizer.encode(text)  # type: ignore
        return len(encoded_text.ids)  # type: ignore
```

- The function appears not to be accurate for newer models
- It would be super useful to either make it or accurate or tell us how we can do it ourselves before sending the request

**Comment by jenan-ant** [comment]
Hi @rbehal! Unfortunately, it's no longer possible to provide ahead-of-time client-side accurate token counts. The server should respond with token counts after the response is completed, but I recognize that this is not ideal when trying to use every last token of the context window. My best advice for now is use heuristic estimates and give yourself a buffer, but we're definitely considering ways of making this a better developer experience.

**Comment by rbehal** [comment]
Thanks for the reply, that seems so strange to me though. What do you mean exactly by "heuristic estimates", do you have a recommendation anywhere?
