### ISSUE TITLE
Claude 3 Sonnet model doesn't require temperature, Top P, Top K input parameters

### ISSUE THREAD

**Issue by sunnygoel87** [anthropics/anthropic-sdk-python#376]
Hi Team,

I noticed in sample examples that Claude v3 Sonnet FM doesn't allow users to pass temperature, Top P and Top K parameters to control the randomness/hallucinations (driven by temperature field) and repetitiveness of words etc. Is that assumption correct ?

**Comment by jenan-ant** [comment]
@sunnygoel87 Hello! All of our models support these parameters. Please see the API reference [here](https://anthropic.readme.io/claude/reference/messages_post).
