### ISSUE TITLE
CLI integration in the SDK

### ISSUE THREAD

**Issue by aanaseer** [anthropics/anthropic-sdk-python#381]
I noticed that the SDK doesn't have a command-line interface (CLI). Introducing a CLI could improve usability, especially for scripting and automation tasks.

If approved, I'm happy to contribute to this enhancement and would like to propose making use of the `argparse` library for implementation. As an initial example, the CLI could facilitate calls to the `messages.create` endpoint as follows:
```
anthropic api messages.create \
	-m <model_name> \
	-g <role1> <content1> \
	-g <role2> <content2> \
	-T <max_tokens>
```

**Comment by rattrayalex** [comment]
Thanks for the suggestion – we don't have current plans for this, but will discuss internally.

**Comment by rattrayalex** [comment]
Anthropic does not plan to do this in the near term, so I'll close this issue for now.
