### ISSUE TITLE
Allow System Prompt Within Messages As Opposed to Top Level Argument

### ISSUE THREAD

**Issue by tarunamasa** [anthropics/anthropic-sdk-python#382]
Most LLM providers (including OpenAI sdk) support "system" as a role within the `messages` argument. allowing `messages` to support this would make it much easier for developers to switch/use your models.

**Comment by DrChrisLevy** [comment]
More generic ask here to support OpenAI compatibility in general.
https://github.com/anthropics/anthropic-sdk-python/issues/384

**Comment by jenan-ant** [comment]
Thanks for the request! Unlike OpenAI's models, our models only support a system prompt before/separately from the conversational turns, and our models also tend to treat system prompts differently from OpenAI's. For better or worse, the models are just different, so we built the API to reflect the best ways to use our models and not be misleading.

**Comment by lrtherond** [comment]
@jenan-anthropic Would it be clarify if the system value is resent over the wire every time a "client.messages.create" call is made? And, if it were sent with the first turn only, would it still be honored in subsequent turns?

**Comment by rublev** [comment]
@jenan-anthropic @lrtherond - would love an answer to this
