### ISSUE TITLE
Will there be a get_embeddings endpoint?

### ISSUE THREAD

**Issue by chaowss** [anthropics/anthropic-sdk-python#383]
In our app, we process large code generation by doing RAG with embeddings. This was possible using OpenAI's API, is it possible to have this feature for the Anthropic API?

**Comment by jenan-ant** [comment]
Hi @chaowss! You can see some documentation about embeddings [here](https://anthropic.readme.io/claude/docs/embeddings). We don't have any public plans other than what's in our documentation.

Also, this repository is used to track issues with the Python SDK, so I'm going to close this issue, but thanks for the request! If the future, this kind of query is best served by [support](https://support.anthropic.com/).
