### ISSUE TITLE
[FEATURE] Is there any future plans to offer OpenAI Client Compatibility?

### ISSUE THREAD

**Issue by DrChrisLevy** [anthropics/anthropic-sdk-python#384]
It would be awesome if we could just change the base_url, api_key, and model and use Anthropic models but through the openai python client. Many other inference tools already provide this. For example: 

https://docs.together.ai/docs/openai-api-compatibility

https://huggingface.co/docs/text-generation-inference/en/messages_api#streaming

https://ollama.com/blog/openai-compatibility

https://docs.endpoints.anyscale.com/examples/work-with-openai/#call-anyscale-endpoints

**Comment by jenan-ant** [comment]
Hi @DrChrisLevy, thanks for the request! I totally hear you that a drop in one-line change would be very nice. However, we're unlikely to provide a server-side OpenAI compatibility layer any time soon. It's possible that we'll build something client-side, but in the meantime, we'd be happy to link to any great community-supported oss wrappers / translation layers, should they be built. It is worth noting that dropping in prompts that were optimized for OpenAI's models is unlikely to get the best performance out of our models. You can see more details in our [Prompt Library](https://docs.anthropic.com/claude/prompt-library).
