### ISSUE TITLE
[Feature] Add Support on Log Probability Value from Returned Response of Claude Models.

### ISSUE THREAD

**Issue by jacklanda** [anthropics/anthropic-sdk-python#392]
How about providing new support for retrieving the log probability of each predicted token by Claude models?

Something just like the same function illustrated in this OpenAI post: [User Logprobs](https://cookbook.openai.com/examples/using_logprobs).

Would you have any thoughts to share about this?

**Comment by jenan-ant** [comment]
Hi @jacklanda, thanks for the feature request!

We don't have any public plans for this, and we use this repository for tracking Python SDK issues, not API feature requests, so I'm going to close this issue.

**Comment by WittmannF** [comment]
Hi @jenan-anthropic ! Thanks! Where can we officially request this API feature?

**Comment by x5a** [comment]
@WittmannF feel free to [open a conversation with our support team and make a feature request](https://support.anthropic.com/en/articles/9015913-how-can-i-contact-support).
