### ISSUE TITLE
[Feature] Add option for logit bias

### ISSUE THREAD

**Issue by dleviminzi** [anthropics/anthropic-sdk-python#393]
This feature is very useful for generating constrained output. Will it be supported at some point? 

Here it is in the openai api for reference: https://platform.openai.com/docs/api-reference/chat/create#chat-create-logit_bias

**Comment by jenan-ant** [comment]
We have no public plans for this, but thanks for the request @dleviminzi! We use this repository to track Python SDK features, not API features, so I'm going to close this out.
