### ISSUE TITLE
Please help me turn off the stream

### ISSUE THREAD

**Issue by DAXwrld** [anthropics/anthropic-sdk-python#395]
Hi!
Please help me fix the code to disable the stream and send responses in a regular message

> async def send_message_stream(self, message) -> None:
>         self.prompt = f"{self.prompt}{HUMAN_PROMPT} {message}{AI_PROMPT}"
>         answer = ""
>         async with self.client.messages.stream(
>           max_tokens=4096,
>           model=self.model,
>           temperature=self.temperature,
>           messages=[
>               {
>                   "role": "user",
>                   "content": self.prompt,
>               }
>             ],
>         ) as stream:
>           async for text in stream.text_stream:
>             answer = f"{answer}{text}"
>             yield answer
>         self.prompt = f"{self.prompt}{answer}"
>         message = await stream.get_final_message()
>         print(message.model_dump_json(indent=2))

**Comment by muhammadahmedzahid** [comment]
You can use the simple function, instead of async and await below is the code for how you can get the simple request and response instead of streaming the response.

```
your_model_name = "claude-3-sonnet-20240229"
your_prompt_sample = "Hello Anthropic?"
client = anthropic.Anthropic(
    api_key="your_api_key",
)
message = client.messages.create(
    model=f'{your_model_name}',
    max_tokens=4096,
    messages=[
        {"role": "user", "content": f'{your_prompt_sample}'}
    ]
)
print(message)
print(message.content[0].text)
```
