### ISSUE TITLE
Is there an extra `\n` in the streaming example?

### ISSUE THREAD

**Issue by alexlyzhov** [anthropics/anthropic-sdk-python#4]
Relevant location:
https://github.com/anthropics/anthropic-sdk-python/blob/3ea420765e29ae6de035070e433ee01165590836/examples/basic_stream.py#L9

https://github.com/anthropics/anthropic-sdk-python/blob/main/examples/basic_sync.py doesn't have one.

**Comment by jacksonkernion** [comment]
Thanks for catching that! Should be fixed shortly...
