### ISSUE TITLE
Feedback regarding model performance

### ISSUE THREAD

**Issue by avin-kavish** [anthropics/anthropic-sdk-python#40]
You model is good but like all models could use improvement.

Is there a way provide feedback about the model to help you improve it? I know there's the option in the chat console, But I am using it through the api so I can't really submit feedback through that. Maybe I can drop you an email.

**Comment by jenan-ant** [comment]
Hi @avin-kavish. Any feedback is welcome through [support@anthropic.com](mailto:support@anthropic.com)!
