### ISSUE TITLE
Question: Is there a way to list the models or check the model?

### ISSUE THREAD

**Issue by sdiazlor** [anthropics/anthropic-sdk-python#401]
Hi! I want to check if a model is an existing one or to be able to list the available models using the SDK. Is there any method to do this? If not, any available API endpoint?

I went through the documentation but I couldn't find anything. I really appreciate any help you can provide.

**Comment by muhammadahmedzahid** [comment]
Here is the documentation page where you can find the model list:

https://docs.anthropic.com/claude/docs/models-overview

and If you want to get the model list using Python SDK you can use the below code to list the models:

```
import inspect
import anthropic
models = inspect.signature(anthropic.Anthropic().messages.create).parameters['model'].annotation
print("Anthropic models", models)
```


![Screenshot 2024-03-20 231313](https://github.com/anthropics/anthropic-sdk-python/assets/54658973/7826d030-6472-4860-9791-f8e401ddf42f)

**Comment by rattrayalex** [comment]
@muhammadahmedzahid is correct. There is not an API to list models at this time.

**Comment by Palisand** [comment]
This will actually get you a list, not a string like the suggestion above produces:
```py
from typing import get_type_hints

list(get_type_hints(anthropic.Anthropic().messages.create)['model'].__args__[1].__args__)
```

However, both methods are quite brittle; a function signature change would probably break them.
