### ISSUE TITLE
AnthropicBedrock does not expose `with_options`

### ISSUE THREAD

**Issue by lckr** [anthropics/anthropic-sdk-python#410]
Hi all,
I'm currently in the process of migrating from `anthropic_bedrock` to `anthropic` and noticed that `client.with_options()...` is not exposed for clients of type `anthropic.AnthropicBedrock`. For clients of the old bedrock library `anthropic_bedrock.AnthropicBedrock.with_options()...` was properly exposed.

Are there any plans to do so and bring the functionality of `anthropic.AnthropicBedrock` more inline with `anthropic.Anthropic`?

Best

**Comment by rattrayalex** [comment]
Thanks for catching this! @RobertCraigie could you take a look?

**Comment by lckr** [comment]
I tried solving this issue with #411, have a look and let me know if this is acceptable for you or needs some more polishing

**Comment by lckr** [comment]
Hi, are there any news on this issue? Happy to improve the MR according to suggestions :)

**Comment by RobertCraigie** [comment]
Sorry for the delay and thanks for the PR!
