### ISSUE TITLE
The usage quota returned by the API is significantly different from the usage quota recorded by the console.

### ISSUE THREAD

**Issue by endlesschasey** [anthropics/anthropic-sdk-python#417]
I think one of the great things about Claude is that you can also collect the officially returned tokens when using streaming output. But after I collected data for three days, I found that the number of tokens for each model displayed on the console and the number of tokens recorded in my background differed by more than 50,000 tokens. I want to know where the problem is, below is my function that streams output

![image](https://github.com/anthropics/anthropic-sdk-python/assets/163229797/f4192d15-efc6-4b61-a6c9-b9928d091c9e)

**Comment by lckr** [comment]
Hi, how do you measure the number of tokens yourself?

As far as I know the old `client.count_tokens(text)` is no longer accurate for the Claude 3 family of models (per #375 and [source](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/_client.py#L266) ).
If you're relying on that method to measure your tokens that might explain the difference.

**Comment by rattrayalex** [comment]
@lckr is correct. Sorry for the inconvenience.
