### ISSUE TITLE
AnthropicBedrock can't handle concurrency

### ISSUE THREAD

**Issue by kevinlu1248** [anthropics/anthropic-sdk-python#418]
I'm running into problems with running multiple AnthropicBedrock instances concurrently. I tried both sharing a global client as well as re-instantiating them / context manager but I'm getting the same bug either way.

I'm running a benchmarking script that works when I run it sequentially but only breaks on concurrent runs.

I get the following error:

```
A process in the process pool was terminated abruptly while the future was running or pending.
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 392, in wait_result_broken_or_wakeup
    result_item = result_reader.recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'
'''
```

Version: `anthropic==0.21.3` on Ubuntu

**Comment by rattrayalex** [comment]
Can you share your script, so we can reproduce? (or a more minimal repro)

Separately, the `APIStatusError` bit sounds like it could be a ~separate bug…

**Comment by kevinlu1248** [comment]
We actually moved off of Bedrock back to normal Anthropic and the problem is gone now, but I'll share the code if we decide to use Bedrock again in the future. But it seemed like the problem really only occurred on Bedrock.

**Comment by rattrayalex** [comment]
Gotcha. I'll go ahead and close then, since I think this is probably going to be difficult for us to track down without a repro case, but if you'd be willing to share a repro script we'd certainly appreciate it and may take a look proactively.
