### ISSUE TITLE
AttributeError in AnthropicBedrock SDK When Accessing 'beta' Attribute for Function Calling

### ISSUE THREAD

**Issue by madtank** [anthropics/anthropic-sdk-python#443]
## Description
I am working with the AnthropicBedrock SDK to leverage advanced features such as function calling within the AWS environment. However, I encountered an `AttributeError` when trying to access the `beta` attribute of an `AnthropicBedrock` object. This seems to indicate a lack of feature parity between the standard Anthropic SDK and the Bedrock SDK, particularly in terms of supporting function calling capabilities.

### Steps to Reproduce
1. Initialize an `AnthropicBedrock` object.
2. Attempt to access the `beta` attribute to utilize function calling features.
3. Encounter `AttributeError: 'AnthropicBedrock' object has no attribute 'beta'`.

Thank you for looking into this issue. I'm looking forward to any updates or workarounds that might be available.

**Comment by rattrayalex** [comment]
When you access the library's `VERSION` property, what is returned? (chances are you're on an old version)

**Comment by madtank** [comment]
> When you access the library's `VERSION` property, what is returned? (chances are you're on an old version)

Works for anthropic sdk but not when I use bedrock version.

AttributeError: 'AnthropicBedrock' object has no attribute 'beta'
pip show anthropic      
Name: anthropic
Version: 0.23.1

Let me know if there is something else I should check.
Thanks

**Comment by rattrayalex** [comment]
Ahh, silly me – the beta features are simply not available under Bedrock yet.
