### ISSUE TITLE
Performance Issue: Cache Boto3 Session in AsyncAnthropicBedrock and AnthropicBedrock

### ISSUE THREAD

**Issue by kazuya-iwami** [anthropics/anthropic-sdk-python#447]
### Current Behavior
When invoking the messages.create() method of AsyncAnthropicBedrock and AnthropicBedrock in an environment utilizing an IAM role, the current implementation retrieves new temporary credentials every time the method is called. This behavior leads to performance overheads and unnecessary latency.

In AWS, it is a common and secure practice to use an IAM role instead of explicitly specifying AWS credentials. However, when messages.create() is called in an environment with an IAM role, the current implementation creates a new boto3.Session() instance each time, which triggers the retrieval of new temporary credentials related with IAM role:

https://github.com/anthropics/anthropic-sdk-python/blob/bd866a1e837febd05b6f5cea322f1c42e29f2d01/src/anthropic/lib/bedrock/_auth.py#L21

### Expected Behavior
To optimize performance and reduce latency, it is recommended to cache the Boto3 session instead of creating a new session for each messages.create() call. Caching the session allows to eliminate the need for redundant credential fetches.

The following resources align with the best practice:
- https://ben11kehoe.medium.com/boto3-sessions-and-why-you-should-use-them-9b094eb5ca8e
- https://github.com/langchain-ai/langchain/blob/51bdfe04e945bdee1f0ad009bae0575e6d2ae811/libs/community/langchain_community/llms/bedrock.py#L423 
    - BedrockChat() in LangChain accepts and caches boto3 client.

### Versions
anthropic 0.23.1

### One of Possible Solutions
1. Modify the AsyncAnthropicBedrock and AnthropicBedrock classes to accept an optional boto3_session parameter in their constructors. This parameter will allow users to provide a pre-configured Boto3 session. 
    - https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/session.html#Session
        - Session class accepts botocore_session as well as aws_access_key_id, aws_secret_access_key, etc. 
3. If the boto3_session parameter is not provided, create a new Boto3 session and cache it within the class instance.
4. Update the _prepare_request() and get_auth_headers() methods to use the cached Boto3 session instead of creating a new session for each invocation.

**Comment by RobertCraigie** [comment]
Thanks for the report. I think we can just add an lru_cache wrapper around the session constructor, e.g.

```py
@lru_cache(maxsize=None)
def _get_session(
    *,
    aws_access_key: str | None,
    aws_secret_key: str | None,
    aws_session_token: str | None,
    region: str | None,
) -> boto3.Session:
    import boto3

    return boto3.Session(
        region_name=region,
        aws_access_key_id=aws_access_key,
        aws_secret_access_key=aws_secret_key,
        aws_session_token=aws_session_token,
    )
```

> Modify the AsyncAnthropicBedrock and AnthropicBedrock classes to accept an optional boto3_session parameter in their constructors. This parameter will allow users to provide a pre-configured Boto3 session.

How helpful would this be? Are there a lot of other session options that would be useful for users to configure?
