### ISSUE TITLE
ERROR: cannot import name 'Anthropic' from 'anthropic

### ISSUE THREAD

**Issue by tonyphoang** [anthropics/anthropic-sdk-python#45]
After running
`pip install anthropic`

and then creating a .py file with the following
`from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT`

I get this error below: 

```
Traceback (most recent call last):
  File "/home/ubuntu/claude_api/main.py", line 1, in <module>
    from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT
ImportError: cannot import name 'Anthropic' from 'anthropic' (/home/ubuntu/claude_api/venv/lib/python3.11/site-packages/anthropic/__init__.py)
```

**Comment by jenan-ant** [comment]
@tonyphoang We're in the process of a new version that hasn't been released to pypi yet, so the README doesn't match the package version you have. You probably want to view the instructions for the v0.2.10 tag: https://github.com/anthropics/anthropic-sdk-python/tree/v0.2.10
