### ISSUE TITLE
Token limit error on API calls less than 200,000 with high volume async api calls

### ISSUE THREAD

**Issue by Amyran1** [anthropics/anthropic-sdk-python#451]
Hello, I'm running a sempahore controlled process with 50 async api calls to the messages API in version anthropic==0.21.3

I've attached a screenshot of the api calls that are less than 200,000 tokens but are returning a token limit errors.

![Screenshot 2024-04-12 at 9 31 04 AM](https://github.com/anthropics/anthropic-sdk-python/assets/131273976/8c5796ed-423e-4e87-b736-a3d1fda58ec3)

**Comment by aaron-lerner** [comment]
Hey @Amyran1, thanks for reporting your issue! Can you head to https://support.anthropic.com and use the message icon in the bottom right corner of the screen to contact support? They'll be better able to assist you there. Thanks!
