### ISSUE TITLE
Output token usage being misreported as 1 when using streaming

### ISSUE THREAD

**Issue by cal-anthropic** [anthropics/anthropic-sdk-python#454]
In the final Message object that the Python SDK constructs when streaming completes (`stream.get_final_message()`). `usage.output_tokens` is always reported as 1 regardless of actual output length.

I believe this object is supposed to be comparable to the Message object you would work with in non-streaming, so I would expect this to report the total output tokens.
![image (6)](https://github.com/anthropics/anthropic-sdk-python/assets/157540744/02de6ae9-48f9-4056-8171-6f7875c86094)

**Comment by rattrayalex** [comment]
Thanks for reporting, we'll take a look!

**Comment by cal-anthropic** [comment]
Let me if you can't repo. I can provide more steps if needed!

**Comment by WesleyYue** [comment]
This is the same issue as https://github.com/anthropics/anthropic-sdk-python/issues/424

**Comment by rattrayalex** [comment]
Thanks, closing as a duplicate.
