### ISSUE TITLE
bedrock: How to tokenizer and count tokenizer?

### ISSUE THREAD

**Issue by kerlion** [anthropics/anthropic-sdk-python#475]
It seems that bedrock has lost a lot of features. such as:
How to do tokenization and count tokenizer?

And is there any api guide? I can find 2 simple code examples.

**Comment by salahaz** [comment]
Any updates on this ?

**Comment by zwluoqi** [comment]
wait

**Comment by bbhorrigan** [comment]
Any update on this coming? I am trying to find some examples.

**Comment by olu-an** [comment]
Hi @kerlion, A good approach you can consider is to conservatively estimate token count based on historical usage e.g. using byte counts and/or mapping from the `usage` field in the response. 

You can find an example response with the `usage` field here: https://docs.anthropic.com/en/api/messages-examples#basic-request-and-response.

Please reach out if you have more questions or need further guidance.

**Comment by olu-an** [comment]
Closing as there hasn't been any activity following the response. Please feel free to reopen if you still have more questions. Thanks!
