### ISSUE TITLE
Scanning is too much

### ISSUE THREAD

**Issue by DonRichards** [anthropics/anthropic-sdk-python#479]
Sorry, I know this isn't the correct place to ask but who do I reach out to discuss the impact Anthropic's claude is having on our institution's sites? Last week felt like a DDos attack. We've since blocked that server and the agent but I'd like to help give a bit a feedback but don't know who to contact. Thanks and sorry for the ticket.

**Comment by rattrayalex** [comment]
Thanks Don, I've passed your feedback along.
