### ISSUE TITLE
Casting to InputSchema drops $defs, causing an InternalServerError

### ISSUE THREAD

**Issue by charles-dyfis-net** [anthropics/anthropic-sdk-python#485]
Consider a tool-calling request with the following schema:

```
{'$defs': {'TestAnimalEnum': {'enum': ['cat', 'dog', 'bird'], 'type': 'string'}},
 'description': 'Describe a pet',
 'properties': {'name': {'description': 'Name of the pet', 'title': 'Name', 'type': 'string'},
                'species': {'allOf': [{'$ref': '#/$defs/TestAnimalEnum'}], 'description': 'species of the pet'}},
 'required': ['species', 'name'],
 'title': 'describe_pet',
 'type': 'object'}
```

Anthropic correctly handles this so long as `$defs` is present; should it be dropped, the `enum` fields become unresolvable, causing an error of the form of:

```none
anthropic.InternalServerError: Error code: 500 - {'type': 'error', 'error': {'type': 'api_error', 'message': 'Internal server error'}}
```

Unfortunately, using `pydantic.TypeAdapter(anthropic.types.beta.tools.tool_param.InputSchema).validate_python(tool.model_json_schema())` drops the `$defs` field from the representation -- after getting the aforementioned HTTP 500 error, if we walk the stack up to `anthropic._base_client.post`, we see a body where `$defs` is not present at all, despite references to it existing:

```
> /nix/store/kpyj1ihx319v9y8kcq0bxvn54zvh52s5-python3-3.12.0-env/lib/python3.12/site-packages/anthropic/_base_client.py(1782)post()
-> return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
(Pdb) pprint.pprint(body)
{'max_tokens': 2048,
 'messages': [{'content': 'Describe a typical pet owned by an 12-year-old', 'role': 'user'}],
 'metadata': NOT_GIVEN,
 'model': 'claude-3-haiku-20240307',
 'stop_sequences': NOT_GIVEN,
 'stream': NOT_GIVEN,
 'system': NOT_GIVEN,
 'temperature': NOT_GIVEN,
 'tools': [{'description': 'Describe a pet',
            'input_schema': {'properties': {'name': {'description': 'Name of the pet',
                                                     'title': 'Name',
                                                     'type': 'string'},
                                            'species': {'allOf': [{'$ref': '#/$defs/TestAnimalEnum'}],
                                                        'description': 'species of the pet'}},
                             'type': 'object'},
            'name': 'PetDescription'}],
 'top_k': NOT_GIVEN,
 'top_p': NOT_GIVEN}
```

...thus explaining the HTTP 500. And, indeed, if the use of `pydantic.TypeAdapter(InputSchema).validate_python(tool.model_json_schema())` is replaced with `typing.cast(InputSchema, tool.model_json_schema())`, the issue is resolved.

This is unfortunate: Users of this library should not need to give up type safety to avoid triggering server-side errors.

**Comment by rattrayalex** [comment]
Thanks for reporting this, and sorry for the problem. We'll look into it soon.

**Comment by RobertCraigie** [comment]
Our type definitions have been fixed in `v0.25.9` :)

**Comment by charles-dyfis-net** [comment]
I only ripped out the "temporary" fix intended to work around this bug today. Doing so, I'm finding that the fix did not in fact resolve the problem:

```
>>> import anthropic.types.tool_param
>>> import pydantic
>>> isa = pydantic.TypeAdapter(anthropic.types.tool_param.InputSchema)
>>> isa.validate_python({"$defs": "yadda", "arbitrary": "value"})
{'$defs': 'yadda', 'arbitrary': 'value'}
>>> isa.validate_python({"type": "object", "$defs": "yadda", "arbitrary": "value"})
{'type': 'object'}
```

If `type` is `object`, we still discard all unrecognized fields.

**Comment by RobertCraigie** [comment]
Ah thanks for the report, this should be fixed in the next release with this change https://github.com/anthropics/anthropic-sdk-python/pull/801/commits/d0961c2fcbe7370f145512facad8aab175798158
