### ISSUE TITLE
Installing Anthropic with PIP on AlmaLinux

### ISSUE THREAD

**Issue by wsj3** [anthropics/anthropic-sdk-python#488]
I'm having trouble with installing anthropic on my remote linux server. I am able to on my local server. The error message I'm getting is:

Collecting anthropic
  Could not find a version that satisfies the requirement anthropic (from versions: )
No matching distribution found for anthropic

Any suggestions?

**Comment by rattrayalex** [comment]
Sorry, this sounds like more of a pip or linux distribution problem – I don't have any suggestions for you.
