### ISSUE TITLE
Empty response from Bedrock Claude Haiku

### ISSUE THREAD

**Issue by nicholas-tutorme** [anthropics/anthropic-sdk-python#499]
Hello, 

I wrote my own wrapper as seen below, and for a majority of my responses (90%), I'm getting message.content = [].

Is this expected? I am not getting errors thrown, it's just returning an empty list. I'm running it in batches of 10 requests at a time, seen below. Please do let me know if there's something obvious I'm not understanding correctly.

row.convert_anthropic() just returns the dict of {role, content} 

Edit: Fixed this by having the whole prompt + content in 'user' role. Using 'assistant' as the final message makes the response enter completion mode, as the docs described, which for some reason can return nothing sometimes.

```
async def async_get_chat_response(
        self,
        prompts: List[ModelMessage],
        user_id: str | None,
        model_name: str,
        **kwargs,
    ) -> Optional[str]:
        max_tokens = kwargs.pop("max_tokens", 1000)
        message: Message = await self.async_client.messages.create(
            messages=[row.convert_anthropic() for row in prompts],
            model=self._get_model_name(model_name),
            # metadata={"user_id": user_id},
            max_tokens=max_tokens,
            **kwargs,
        )
        if len(message.content) == 0:
            return None
        return message.content[0].text
```

```
for row in rows:
  if row['passageId'] not in completed:
    tasks.append(client.async_get_chat_response([ModelMessage(row['content'], 'user'), ModelMessage(prompt, 'assistant')], 'system', 'claude-3-haiku@20240307', temperature=0.2, max_tokens=64))

chunkSize = 10

print("executing tasks", len(tasks))

with open('passage_embedding_concept.jsonl', 'a') as f:
  for i in tqdm(range(0, len(tasks), chunkSize)):
    realI = i * chunkSize
    responses = await asyncio.gather(*tasks[realI:realI+chunkSize])
    _rows = rows[realI:realI+chunkSize]
    for index, response in enumerate(responses):
      if response is not None and len(response) > 0:
        f.write(json.dumps({
          **_rows[index],
          'concepts': response.split('\n')
        }) + '\n')
```

**Comment by xhw1** [comment]
@nicholas-tutorme Hi Nicholas can you please share the document where you saw "Using 'assistant' as the final message makes the response enter completion mode"?

**Comment by nicholas-tutorme** [comment]
https://docs.anthropic.com/en/api/messages

" If the final message uses the assistant role, the response content will
continue immediately from the content in that message. This can be used to
constrain part of the model's response."

Hope this helps.
