### ISSUE TITLE
Please add an endpoint for getting account balance.

### ISSUE THREAD

**Issue by p-i-** [anthropics/anthropic-sdk-python#505]
Please add an endpoint for getting account balance. e.g. `/balance` or `/account_details`.

Many of us are creating products that use Anthropic's HTTP API where the user provides their API key.

A good UX would be for the user to see their remaining balance.

A user that is prepaying to their account will suffer a bad UX when their balance runs out.

As an analogy, when my laptop battery is low, my machine doesn't suddenly power down while I am in the middle of a task. Instead I can observe the battery charge on my system tray, and a notification appears when it reaches 5%.

This is a healthy UX.

PS:
It would be nice to have an `/account_details` endpoint that includes a list of timestamped API calls and their associated costs and IPs, as well as any other information that the user can retrieve from the web portal. However I can see this might be contentious when it comes to granting API keys for others to use. You'd have to tick checkboxes when creating an API key to grant individual functionalities.

And that would be nice. If I could create an API key, uncheck "master-mode", set a per-day limit of $5, that would be nice. I could provide a capped API key to each user when I distribute my product. Or I could grant API keys to my team.

And if I could create a "master-mode" API key for my own use, which lets me view my account details as well as details of any other API key I have generated, that would be nice.

But this starts to become a medium-to-large sized task.

Just providing a `/balance` endpoint should be trivial, and I don't see any downside / contention.

**Comment by RobertCraigie** [comment]
Thanks for the feature request! I'm going to close this as it applies to the API and not the SDK but I've forwarded it to the Anthropic team.

**Comment by the-najjar** [comment]
Is there a reason for why this is not planned? @RobertCraigie

**Comment by aaron-lerner** [comment]
Hi @the-najjar, this issue was closed because it's outside the scope of the SDK, which is a client of the API as it exists today. Rest assured that we're aware of feedback like this and are definitely interested in expanding the utility of the API.

**Comment by p-i-** [comment]
The problem is that for us outsiders there isn't any clear channel of communication to whichever anthropic department is responsible for building out the API.

It was my hope that someone in THIS Anthropic team would connect with someone in THAT Anthropic team, and as a result the functionality would appear. Isn't the SDK team gona be super-close to the API team? You're literally building a wrapper around the API.

But surely someone in this team can see the value of a `/balance` endpoint? Enough to push it through anthropic internal channels...

It is as if Anthropic has produced a door without a handle. And I'm saying "please could we have a handle for the door", and you are saying "<shrug> we just fit the doors, we don't make them, that's another department. Not our remit!"

And the result is that after six months there is still no handle on the door.

I am only here because I tried the AI Assistant, and it threw me straight back to my old issue. So at least the AI assistant is working, I suppose.

Please can someone within the Anthropic spaceship reading this see the obvious value and utility in exposing a `/balance` endpoint, and step up?

**Comment by rothos** [comment]
@p-i- It's not an official API endpoint, but by looking at the network requests on the Billing page I was able to determine that you can get the account balance by going here:

```
https://console.anthropic.com/api/organizations/%ORGANIZATION_ID%/prepaid/credits
```

where `%ORGANIZATION_ID%` is the org ID as seen at the bottom of this page: 
[https://console.anthropic.com/settings/organization]()

The JSON result looks like this:
```
{"amount":456}
```
and is denominated in cents (so the above indicates $4.56 in credits). Obviously you have to provide the correct auth in the request (I'm not exactly sure how to do that, as I've only tested this in the browser while logged into the Anthropic console).

**Comment by matebenyovszky** [comment]
thanks @rothos , that works, if I am authenticated in the browser, but need to find a way to automate this from backend python code..

**Comment by frankmeeuwsen** [comment]
What would be the way to access this programmatically? I tried it with the proper Organization_ID and added the API key in the header through curl, but I get a permission error. Did anyone get this to work?

**Comment by DavidIfebueme** [comment]
hi. doing a quick search and thought i should ask.
did this ever get a dedicated endpoint without the honestly unnecessary anthropic user auth layer

**Comment by jeinselen** [comment]
Yeah, I'm looking for this too!

**Comment by Pfiver** [comment]
Hm. Why is this not planned? I want it.

**Comment by jukwaphil1** [comment]
Where is the API feature request page please? I really need this too. Thanks

**Comment by benknight** [comment]
This is clearly a dark pattern. Anthropic would like you to enable auto-reload and reap the benefits even if something unexpectedly causes runaway usage.
