### ISSUE TITLE
Tool call containing array is not streamed

### ISSUE THREAD

**Issue by jackmpcollins** [anthropics/anthropic-sdk-python#509]
When streaming a tool call that contains an array, the array is not streamed / all the chunks arrive at once. Instead, the chunks should arrive as they are generated, so that they can be processed without waiting for the response - the reason for using streaming. This is needed to make object streaming work in https://github.com/jackmpcollins/magentic

Code to reproduce (occasionally hits content filtering policy error, so might require some retries)

```python
import time

from anthropic import Anthropic

client = Anthropic()


with client.beta.tools.messages.stream(
    max_tokens=1024,
    model="claude-3-opus-20240229",
    messages=[{"role": "user", "content": "List all the countries in the world."}],
    tools=[
        {
            "name": "create_list",
            "description": "",
            "input_schema": {
                "properties": {
                    "value": {
                        "title": "Value",
                        "type": "array",
                        "items": {"type": "string"},
                    }
                },
                "required": ["value"],
                "type": "object",
            },
        },
    ],
    tool_choice={"type": "tool", "name": "create_list"},
) as stream:
    for chunk in stream:
        print(time.time(), chunk)
```

Output showing the first `ToolsBetaContentBlockDeltaEvent` arrives at 1716168421, but the second one arrives 18 seconds later at 1716168439 along with all the following chunks.

```
1716168421.8091662 MessageStartEvent(message=Message(id='msg_012G224LsYEXGJh3YMLRxKEi', content=[], model='claude-3-opus-20240229', role='assistant', stop_reason=None, stop_sequence=None, type='message', usage=Usage(input_tokens=375, output_tokens=10)), type='message_start')
1716168421.8095412 ToolsBetaContentBlockStartEvent(content_block=ToolUseBlock(id='toolu_014zNHBpUng75wdSLEu7Dkhe', input={}, name='create_list', type='tool_use'), index=0, type='content_block_start')
1716168421.809738 ToolsBetaContentBlockDeltaEvent(delta=InputJsonDelta(partial_json='', type='input_json_delta'), index=0, type='content_block_delta')
1716168439.369919 ToolsBetaContentBlockDeltaEvent(delta=InputJsonDelta(partial_json='{"value', type='input_json_delta'), index=0, type='content_block_delta')
1716168439.37115 ToolsBetaContentBlockDeltaEvent(delta=InputJsonDelta(partial_json='": "Afgh', type='input_json_delta'), index=0, type='content_block_delta')
1716168439.371315 ToolsBetaContentBlockDeltaEvent(delta=InputJsonDelta(partial_json='anistan\\n', type='input_json_delta'), index=0, type='content_block_delta')
1716168439.371479 ToolsBetaContentBlockDeltaEvent(delta=InputJsonDelta(partial_json='Albania\\nAlg', type='input_json_delta'), index=0, type='content_block_delta')
...
```

**Comment by jenan-ant** [comment]
Hi @jackmpcollins, thanks for the request! This is a limitation of the current models and definitely on our roadmap. See docs [here](https://docs.anthropic.com/en/api/messages-streaming#streaming-request-with-tool-use):

> Note: Our current models only support emitting one complete key and value property from `input` at a time. As such, when using tools, there may be delays between streaming events while the model is working. Once an `input` key and value are accumulated, we emit them as multiple `content_block_delta` events with chunked partial json so that the format can automatically support finer granularity in future models.

Since this is a server-side request and not specific to the SDK, I'm going to close this issue.
