### ISSUE TITLE
Support Tool Choice Type: None

### ISSUE THREAD

**Issue by tarunamasa** [anthropics/anthropic-sdk-python#549]
Allow a version of tool choice that is none (this allows you to pass tools in but ensure that no tools are called. This is similar functionality to the openai SDK).

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying Anthropic API and not the SDK, so I'm going to go ahead and close this issue.

I recommend joining the [community discord](https://anthropic.com/discord) or for more details on API support and assistance, see [this support article](https://support.anthropic.com/en/articles/8114535-where-can-i-go-for-api-support-and-assistance).
