### ISSUE TITLE
Timeout error when calling claude-100k using long input

### ISSUE THREAD

**Issue by FranxYao** [anthropics/anthropic-sdk-python#55]
Hi, 

I was trying to call Claude-v1.3-100k (Clong) using a very long input (119923 tokens from OpenAI tiktokenizer). I encountered a "timeout" error which after debugging, should trace back to 

DEFAULT_TIMEOUT = Timeout(timeout=60.0, connect=5.0)

in https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/_base_client.py#L84C1-L84C1

where the timeout is 60 seconds but Clong requires more than 60s to compute (in my case, 93s after I modified the timeout variable). 

I feel like this should be a general issue when calling Claude for long-context. I considered adding a pull request extending timeout to 5 minutes but I also feel like probably letting users to decide timeout as an argument might also be a solution. So I just raise up the issue here and feel free to ask for more clarification / details

**Comment by rattrayalex** [comment]
Sorry about this! We'll be raising the default timeout substantially quite soon. Thanks for your report.
