### ISSUE TITLE
Support Parallel Tool Calls = False

### ISSUE THREAD

**Issue by tarunamasa** [anthropics/anthropic-sdk-python#553]
Ability to be able to force only one single tool output (not many) 
Similar to the `parallel_tool_calls` param in the OpenAI sdk.

**Comment by redvivi** [comment]
\+ 1, but on my end needed on the REST endpoint. I assume both will go along.

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying Anthropic API and not the SDK, so I'm going to go ahead and close this issue.

I recommend joining the [community discord](https://anthropic.com/discord) or for more details on API support and assistance, see [this support article](https://support.anthropic.com/en/articles/8114535-where-can-i-go-for-api-support-and-assistance).

**Comment by RobertCraigie** [comment]
The `disable_parallel_tool_use` request param was added in `v0.35.0`!
