### ISSUE TITLE
API Requests Within Existing Projects

### ISSUE THREAD

**Issue by artwist-polyakov** [anthropics/anthropic-sdk-python#561]
Hello,

It would be incredibly useful to have the ability to make API requests within the context of existing projects. Given that projects contain pre-prepared data, this feature would greatly enhance the usefulness and efficiency of API responses.

Is there any plan to implement such an enhancement in the near future?

Thank you!

**Comment by nsmccandlish** [comment]
Hi @artwist-polyakov, thanks for the feature request!

We don't have any public plans for this, and we use this repository for tracking Python SDK issues, not API feature requests, so I'm going to close this issue.

**Comment by artwist-polyakov** [comment]
> Hi @artwist-polyakov, thanks for the feature request!
> 
> 
> 
> We don't have any public plans for this, and we use this repository for tracking Python SDK issues, not API feature requests, so I'm going to close this issue.

Hello,

Thank you for your answer.

Do you happen to know the way to make an API feature request?
