### ISSUE TITLE
AnthropicVertex does not expose `with_options`

### ISSUE THREAD

**Issue by dlebech** [anthropics/anthropic-sdk-python#566]
### What is it

The `AnthropicVertex` and `AsyncAnthropicVertex` clients do not seem to expose `with_options(...)` like the other clients.

Similar previous issue for Bedrock: https://github.com/anthropics/anthropic-sdk-python/issues/410

### Example

```shell
> client.with_options(max_retries=num_retries).messages.create(...)
AttributeError: 'AsyncAnthropicVertex' object has no attribute 'with_options'
```

Thank you.

**Comment by rattrayalex** [comment]
Thanks for the report. We'll try to fix this soon, but a PR would be welcome.

**Comment by dlebech** [comment]
Thanks @rattrayalex . Yes ok, I think can manage that. I will have a PR ready later today :+1:

**Comment by RobertCraigie** [comment]
Thanks for the PR @dlebech!
