### ISSUE TITLE
Error in the vertex AI documentation

### ISSUE THREAD

**Issue by karthikdatta98** [anthropics/anthropic-sdk-python#570]
https://github.com/anthropics/anthropic-sdk-python/blob/main/README.md - You can then import and instantiate a separate **AnthropicVertex/AsyncAnthropicVertexAsync** class, which has the same API as the base Anthropic/AsyncAnthropic class.

It is AsyncAnthropicVertex and not AsyncAnthropicVertexAsync

Please make the change.

**Comment by rattrayalex** [comment]
Thank you for filing! A PR would be welcome here; otherwise, we hope to fix soon.

**Comment by karthikdatta98** [comment]
https://github.com/anthropics/anthropic-sdk-python/pull/579
Raised and I think it is merged. Closing the issue.
