### ISSUE TITLE
Missing token count feature

### ISSUE THREAD

**Issue by erlapso** [anthropics/anthropic-sdk-python#571]
Right now it's not possible to make an API call to determine the number of tokens for a given string. It is possible to know the number of used tokens _after_ a call is made with `usage` but it's not possible to do so _before_ making a call. Other providers do have this feature, either as a native Python package or as a dedicated API call that is cheaper than the full-fledged `/chat` endpoint.

**Why would it be helpful?**
Sometimes you need to split your task into multiple prompts when dealing with very long text. For example, when you need to summarize and extract data from a 200-pages document. In that scenario, having a token counter would allow developers to split the content meaningfully in order to have enough tokens left for a response.

**Comment by rattrayalex** [comment]
Closing as a duplicate: https://github.com/anthropics/anthropic-sdk-python/issues/375#issuecomment-1999982035
