### ISSUE TITLE
Vertex "Could not resolve API token from the environment"

### ISSUE THREAD

**Issue by kkhangv** [anthropics/anthropic-sdk-python#586]
<img width="627" alt="Screenshot 2024-07-10 at 4 56 29 PM" src="https://github.com/anthropics/anthropic-sdk-python/assets/44094672/470faa05-144f-4ab8-892d-5ac8d839a2c5">
For some reasons after the update, Vertex now keeps asking for API Tokens but we are using GCP service account to authorize VertexAI and it was fine until this morning. Did the new release change or require something new?

**Comment by kkhangv** [comment]
I downgraded to the previous version and it worked. Hopefully not a wide spread Issue.

**Comment by RobertCraigie** [comment]
Hey @kkhangv, sorry about this, can you share more details on how you're authenticating? Where is that error coming from - is there a stack trace?

Nothing new should be required in the last release but we did [change](https://github.com/anthropics/anthropic-sdk-python/pull/573/files#diff-5a8218ad56766298572483a9849052a7908d041975753474f94480bb62dad4d0) some of our logic around  handling google credentials but it was not intentionally breaking.

**Comment by kkhangv** [comment]
Using oauth2: 

`from google.oauth2 import service_account
from google.auth.credentials import Credentials


def get_gcp_credentials() -> tuple[Credentials, str, str]:
    key_dict = {`

**Comment by hantusk** [comment]
Just hit this as well. Can confirm downgrading to `anthropic==0.30` works here.

Service account has the "Vertex AI User" role in gcp, and my auth is set up like this:
```
claude = AnthropicVertex(region=region, project_id=project, credentials=google.auth.load_credentials_from_file('credentials.json', scopes=["https://www.googleapis.com/auth/cloud-platform"])[0])
```

**Comment by RobertCraigie** [comment]
Thanks both, unfortunately I'm struggling to reproduce this but I've merged a change that I think should fix this issue.

Would anyone be able to test this out and let me know if it works for you? thanks!
```
python -m pip install -U git+https://github.com/anthropics/anthropic-sdk-python@next
```

**Comment by hantusk** [comment]
Yup that works for me 👍 consider having a separate version number or suffix for the `next` branch.

**Comment by RobertCraigie** [comment]
Awesome, thanks!

> consider having a separate version number or suffix for the next branch.

Ah we have a separate PR that includes the version bump: https://github.com/anthropics/anthropic-sdk-python/pull/595

So until that's released (hopefully later today) you can use that branch if you want the version bump
```
python -m pip install -U git+https://github.com/anthropics/anthropic-sdk-python@release-please--branches--main--changes--next
```

**Comment by RobertCraigie** [comment]
`v0.31.2` has been released with this fix!

**Comment by kkhangv** [comment]
Amazing. Save lots of people! :)
