### ISSUE TITLE
Is there a way to manage Claude Projects in Web UI via the API?

### ISSUE THREAD

**Issue by MacHu-GWU** [anthropics/anthropic-sdk-python#598]
For example, I want to see if I can use a Python client to:

1. list all Claude projects I created.
2. list all Claude chat sessions, sort by last active time.
3. create / get details / update / delete (archive) a Claude project.

These APIs are powerful for automation and they are easy to implement. They don't call the backend LLM model at all.

**Comment by nsmccandlish** [comment]
Hi @MacHu-GWU, thanks for the feature requests!

We don't have any public plans for this, and we use this repository for tracking Python SDK issues, not API feature requests, so I'm going to close this issue.

**Comment by esquivalient** [comment]
Where is the correct place to request API features? I also want a Projects API and it's not clear which support/feedback mechanism I'm supposed to use.

**Comment by MacHu-GWU** [comment]
@esquivalient I tried using headless browser automation and it works, but very ugly.
