### ISSUE TITLE
What is the correct way to use streaming?

### ISSUE THREAD

**Issue by tcapelle** [anthropics/anthropic-sdk-python#616]
Hello,

In the Anthropic [docs](https://docs.anthropic.com/en/api/messages-streaming#streaming-with-sdks) it is suggested to use:
```python
client.messages.stream
```
but in the [Readme](https://github.com/anthropics/anthropic-sdk-python?tab=readme-ov-file#streaming-responses) it is recommended to use:
```python
stream = client.messages.create(
    ...
    stream=True)
```
which is the more forward compatible way? Also the processing of the stream is different

**Comment by RobertCraigie** [comment]
They are both correct and serve different purposes.

`.create(stream=True)` just provides an iterator over the raw API response.

`.stream()` is a wrapper over `.create(stream=True)` that automatically accumulates the events into a final message object for you among other things.

Here are the docs for `.stream()`: https://github.com/anthropics/anthropic-sdk-python/blob/main/helpers.md
