### ISSUE TITLE
AnthropicBedrock supports Prompt Caching

### ISSUE THREAD

**Issue by codecrack3** [anthropics/anthropic-sdk-python#638]
I tried passing "cache_control": {"type": "ephemeral"} in messages but it is not working
<img width="551" alt="image" src="https://github.com/user-attachments/assets/2ae9a233-632d-4d86-a50d-580c8975ee56">

**Comment by RobertCraigie** [comment]
The Bedrock API doesn't support prompt caching yet unfortunately. The SDK will be updated when it does :)
