### ISSUE TITLE
Docs typo: "isight" instead of "insight"

### ISSUE THREAD

**Issue by levibe** [anthropics/anthropic-sdk-python#641]
1. On page: [Giving Claude a role (system prompts)](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/system-prompts)
2. Under: "How to give Claude a role"
3. Typo: "data scientist specializing in customer **isight**"

<img width="965" alt="Screenshot 2024-08-15 at 6 24 45 PM" src="https://github.com/user-attachments/assets/8a1593ce-ff85-4e17-8af4-e8574e9a1fac">

**Comment by RobertCraigie** [comment]
Thanks for the report, I've forwarded this to the Anthropic team.
