### ISSUE TITLE
Provide support for token counting for Claude 3.5+ models

### ISSUE THREAD

**Issue by areibman** [anthropics/anthropic-sdk-python#642]
Currently, the `count_tokens` function only works for old models (i.e. 2.1 and below).

This has led to people creating "unofficial" tokenizers:
https://github.com/javirandor/anthropic-tokenizer

Several people on Reddit have also noted this issue:
https://www.reddit.com/r/ClaudeAI/comments/1bgg5v0/how_do_you_countestimate_token_inputoutputs_with/

Solution:
Create support for Claude 3+ models by publicizing the tokenizer vocabulary

**Comment by nsmccandlish** [comment]
Closing as a duplicate https://github.com/anthropics/anthropic-sdk-python/issues/375#issuecomment-1999982035
