### ISSUE TITLE
Feat: Alternate key

### ISSUE THREAD

**Issue by akshit0201** [anthropics/anthropic-sdk-python#646]
I often hit usage limits on my api keys.
Requesting a way to configure alternate key in the Anthropic config.

**Comment by RobertCraigie** [comment]
You can change your API key like this:
```py
client = Anthropic(api_key='...')
new_client = client.with_options(api_key='...')
```
or are you asking for something else?

**Comment by akshit0201** [comment]
Didn't realize this option existed.
Thanks for your help!
