### ISSUE TITLE
Sending a file as part of the prompt

### ISSUE THREAD

**Issue by taesiri** [anthropics/anthropic-sdk-python#66]
Hello,

I was wondering if the current SDK supports sending a file (PDF, txt) as part of the prompt. We can certainly read the content of the file and append it to the prompt, but I was wondering if this is something that the SDK would support directly.

Thanks

**Comment by rattrayalex** [comment]
Sorry, this is neither supported nor planned in the SDK; you'll have to assemble the text yourself.
