### ISSUE TITLE
Bug Report - Fetch failure due to the phrase "web.config"

### ISSUE THREAD

**Issue by JoshJarabek7** [anthropics/anthropic-sdk-python#70]
Hi,

To start off, I'd like to say I'm loving Claude so far, as it's more up to date than OpenAI's models. I'm planning on integrating Claude in my startup's technology for sure.

This probably isn't the most ideal place to put this issue and you can close it out if so, but I was having a hard time figuring out where to report bugs to for Claude via the online chat beta. Claude gave me numerous suggestions and links, but none of them were real.

I was using Claude chat online for navigating Azure and a specific phrase/word causes fetch failure. It had made 3 separate suggestions on fixing a bug I'm having. One of them was checking the web.config for the app service. I asked it to expand on all three suggestions in the same message and it kept failing, so I decided to go one-by-one. Using "web.config" in the chat was deemed the culprit. 

It's probably a security rule built in or something, and probably a phrase that would appear very rarely, but I wanted to report it just in case.

**Comment by rattrayalex** [comment]
Thank you @JoshJarabek7 ! For reporting bugs in Claude, please write in to https://support.anthropic.com
