### ISSUE TITLE
Swagger/OpenAPI specification

### ISSUE THREAD

**Issue by HavenDV** [anthropics/anthropic-sdk-python#71]
Hey. We want to release an SDK for C# and would like to know if you have an official Swagger/OpenAPI spec? I see that your SDKs are generated with Stainless and the OpenAPI spec, but didn't find it publicly available.
I think it would be great if this is available in a separate repository and updated according to the latest changes, like OpenAI - https://github.com/openai/openai-openapi

**Comment by jenan-ant** [comment]
Hi @HavenDV. We'll likely do this eventually but it's not an immediate priority for us. Thanks for asking!
