### ISSUE TITLE
Send the transparency PNG but look like the "API" convert it to white background PNG.

### ISSUE THREAD

**Issue by Pjumpod** [anthropics/anthropic-sdk-python#714]
I submit the pictures by "client.messages.create" and set the image_type = "image/png"
but when ask the description, all images return the white background in description.
all images should be expect to be transparency or blank background.

![F_ON_BLANK_BACKGROUND](https://github.com/user-attachments/assets/c735fce5-4844-4fe9-bf7c-22c33b3886ab)
![jirawatfoto_3107_41_Assorted_green_leaves_various_shapes_and__ON_BLANK_BACKGROUND](https://github.com/user-attachments/assets/76d608d2-65c0-4753-bdcc-9dba93cc76e8)
![T_ON_BLANK_BACKGROUND](https://github.com/user-attachments/assets/66b6ac02-bc1b-4960-97cb-ba59ecd69dc2)

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying Anthropic API and not the SDK, so I'm going to go ahead and close this issue.

I recommend joining the [community discord](https://anthropic.com/discord) or for more details on API support and assistance, see [this support article](https://support.anthropic.com/en/articles/8114535-where-can-i-go-for-api-support-and-assistance).
