### ISSUE TITLE
Claude Mac App Excessive Cache Size

### ISSUE THREAD

**Issue by austinmw** [anthropics/anthropic-sdk-python#734]
**Note:** Not sure if this is the right place, but there’s no dedicated repo I can see for the Anthropic macOS app.

The app's `~/Library/Caches/com.anthropic.claudefordesktop.ShipIt` folder is already consuming over 40GB of disk space on my machine after only a few days, with numerous old update files (~445MB each) not being cleared automatically (screenshot attached). A cleanup mechanism for these files would be helpful.

![image](https://github.com/user-attachments/assets/dd2712ec-0b52-426f-b156-dc658c14977a)

**Comment by anaisbetts** [comment]
Hey @austinmw, is it possible that the permissions on `/Applications/Claude.app` are incorrect or owned by another user? In the meantime, you can of course delete this folder and get your 40GB back, apologies for the trouble!

**Comment by aaron-lerner** [comment]
Thanks for the feedback, it's been passed along! For future reference, `Help -> Submit Feedback` in the menubar will take you to a google form you can fill out for this kind of feedback.
