### ISSUE TITLE
ImportError: cannot import name 'ModelField' from 'pydantic.fields'

### ISSUE THREAD

**Issue by iwtu** [anthropics/anthropic-sdk-python#74]
Hello. 
I have import error when I am trying to use Anthropic. 

```Traceback (most recent call last):
  File "/Users/iwtu/repos/expensive-faqbot/claude2.py", line 1, in <module>
    from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT
  File "/Users/iwtu/.pyenv/versions/3.11.3/envs/expensive-faqbot/lib/python3.11/site-packages/anthropic/__init__.py", line 3, in <module>
    from . import types
  File "/Users/iwtu/.pyenv/versions/3.11.3/envs/expensive-faqbot/lib/python3.11/site-packages/anthropic/types/__init__.py", line 5, in <module>
    from .completion import Completion as Completion
  File "/Users/iwtu/.pyenv/versions/3.11.3/envs/expensive-faqbot/lib/python3.11/site-packages/anthropic/types/completion.py", line 3, in <module>
    from .._models import BaseModel
  File "/Users/iwtu/.pyenv/versions/3.11.3/envs/expensive-faqbot/lib/python3.11/site-packages/anthropic/_models.py", line 11, in <module>
    from pydantic.fields import ModelField
ImportError: cannot import name 'ModelField' from 'pydantic.fields' (/Users/iwtu/.pyenv/versions/3.11.3/envs/expensive-faqbot/lib/python3.11/site-packages/pydantic/fields.py)```

```pip show anthropic
Name: anthropic
Version: 0.3.1
Summary: Client library for the anthropic API
Home-page: https://github.com/anthropics/anthropic-sdk-python
Author: Anthropic
Author-email: support@anthropic.com
License: MIT
Location: /Users/iwtu/.pyenv/versions/3.11.3/envs/expensive-faqbot/lib/python3.11/site-packages
Requires: anyio, distro, httpx, pydantic, tokenizers, typing-extensions
Required-by:```

```pip show pydantic
Name: pydantic
Version: 2.0.3
Summary: Data validation using Python type hints
Home-page:
Author:
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>
License:
Location: /Users/iwtu/.pyenv/versions/3.11.3/envs/expensive-faqbot/lib/python3.11/site-packages
Requires: annotated-types, pydantic-core, typing-extensions
Required-by: anthropic, fastapi, pydantic-settings```

**Comment by rattrayalex** [comment]
This is happening because a previous version of this library did not pin our version of pydantic to version <2, which released breaking changes. 

It looks like you're on 0.3.1 of this library; this was fixed in 0.3.2, and the [latest release](https://github.com/anthropics/anthropic-sdk-python/releases) is 0.3.4, which I recommend upgrading to.

**Comment by iwtu** [comment]
It looks like that pydantic-settings is causing the problem.

**Comment by rattrayalex** [comment]
We're looking into adding support for pydantic v2, but ensuring thorough support is not trivial. 

In the meantime, I recommend upgrading to `anthropic` version `0.3.4`, which should cause your pydantic version to fall back to 1.9.x. Does that work for you?

**Comment by iwtu** [comment]
without pydantic-settings yes. 

But the following requirements files will install pydantic 2.0.3.
Also interesting about this file that if you swich order pydantic-settings and anthropic, then pip install -r will throw some weird error. 


```
openai
beautifulsoup4
fastapi
google-cloud-aiplatform
uvicorn[standard]
gunicorn
pydantic-settings
anthropic
```

**Comment by rattrayalex** [comment]
You may want to pin `pydantic-settings` to a version <2, like this:
```
pydantic-settings==1.99
```

**Comment by iwtu** [comment]
I tried. It didn't help :/

**Comment by rattrayalex** [comment]
Sorry to hear that; Python dependency management can be a pain. You might try using `poetry` to produce a `poetry.lock` file, which could help you discover the reason that `pydantic` v2 is still being used, and fix it. 

If this problem persists after you have successfully downgraded to use pydantic v1 in your project, please reopen this issue and include the new values of `pip show anthropic` and `pip show pydantic`.

**Comment by iwtu** [comment]
I found it. It's very unintuitive. pydantic-settings v1.99 is for pydantic v2.

**Comment by rattrayalex** [comment]
Glad to hear you figured it out! What version of pydantic-settings worked correctly for you?

**Comment by iwtu** [comment]
I needed only simple call so instead of fighting all this I replaced it with HTTP request :)
