### ISSUE TITLE
Is there a Rust SDK?

### ISSUE THREAD

**Issue by libertyteeth** [anthropics/anthropic-sdk-python#747]
I couldn't find one, so I'm making one, based on this.  Let me know if one already exists, and/or you're interested.  Thanks!

**Comment by libertyteeth** [comment]
Cline split the task into six stages.  I am now halfway through.

**Comment by RobertCraigie** [comment]
Unfortunately there isn't a Rust SDK yet. We're actively working on Java & Ruby SDKs and there are a couple of other languages in our pipeline before Rust.

Please share what you end up with! Interested to see what it looks like.

**Comment by libertyteeth** [comment]
> Unfortunately there isn't a Rust SDK yet. We're actively working on Java & Ruby SDKs and there are a couple of other languages in our pipeline before Rust.
> 
> Please share what you end up with! Interested to see what it looks like.

Thank you!  Will do.  It is well underway, and is something I need for further efforts.

Currently on v3.  Amazing developing software 100x faster.  It'll be MIT licensed.
