### ISSUE TITLE
Urgent Help Needed: 529-overloaded-error

### ISSUE THREAD

**Issue by AliMaastech** [anthropics/anthropic-sdk-python#757]
For a chat bot that needs to go live in the next 24 hours we often get the following Error the middle of the conversation:
{“type”:“error”,“error”:{“details”:null,“type”:“overloaded_error”,“message”:“Overloaded”}}.

Using “@anthropic-ai/sdk”: “^0.27.3"

Our usual input token length per minute can be around 5k-30k per minute. Implemented retry solution but still get it, also sometimes long delays. API calls from us can be 2-3 per conversation and expecting at peak to have 3-4 conversations simultaneously.
Will really appreciate urgent feedback. Also, can this be resolved by implementing prompt cache? Or any other techniques?

**Comment by RobertCraigie** [comment]
Hey @AliMaastech, sorry for the delayed response. Yes prompt caching could help if it's applicable to your use case.

For more timely API support I recommend joining the [community discord](https://anthropic.com/discord) or for more details on API support and assistance, see [this support article](https://support.anthropic.com/en/articles/8114535-where-can-i-go-for-api-support-and-assistance) and then contact the support team.
