### ISSUE TITLE
httpx: TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by german-muzquiz** [anthropics/anthropic-sdk-python#766]
A new version of the `httpx` library has been just released (`0.28.0`): https://github.com/encode/httpx/releases/tag/0.28.0

This new version removed the keyword argument `proxies` from the class `httpx.AsyncClient`, which the antrophic sdk uses to create clients.

How to reproduce:
```
client = AsyncAnthropicBedrock()
```
Exception:
```
    client = AsyncAnthropicBedrock()
../../.venv/lib/python3.12/site-packages/anthropic/lib/bedrock/_client.py:283: in __init__
    super().__init__(
../../.venv/lib/python3.12/site-packages/anthropic/_base_client.py:1437: in __init__
    self._client = http_client or AsyncHttpxClientWrapper(
../../.venv/lib/python3.12/site-packages/anthropic/_base_client.py:1334: in __init__
    super().__init__(**kwargs)
E   TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
```
Pinning the httpx version to `0.27.2` fixes the issue.

**Comment by RobertCraigie** [comment]
@german-muzquiz please try the latest version of this library, the issue should be fixed.

**Comment by german-muzquiz** [comment]
It's working, thanks!
