### ISSUE TITLE
TypeError: Client.__init__() got an unexpected keyword argument 'proxies' 

### ISSUE THREAD

**Issue by charliemday** [anthropics/anthropic-sdk-python#767]
## What's the Issue

I'm getting the following error:

```
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

I suspect it's down to `httpx` release: https://github.com/encode/httpx/releases/tag/0.28.0 removing the deprecated `proxies` argument. OpenAI's Python SDK had a very similar issue (https://github.com/openai/openai-python/releases/tag/v1.55.3).

**Comment by RobertCraigie** [comment]
@charliemday this should be fixed in the latest release!
