### ISSUE TITLE
SyncHttpxClientWrapper proxies argument incompatiple with latest httpx.AsyncClient

### ISSUE THREAD

**Issue by arsenopt** [anthropics/anthropic-sdk-python#773]
I'm getting the following keyword argument error
```
  File "/root/.cache/pypoetry/virtualenvs/screen-iq-8D-jOGkB-py3.9/lib/python3.9/site-packages/anthropic/lib/bedrock/_client.py", line 130, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/screen-iq-8D-jOGkB-py3.9/lib/python3.9/site-packages/anthropic/_base_client.py", line 846, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/root/.cache/pypoetry/virtualenvs/screen-iq-8D-jOGkB-py3.9/lib/python3.9/site-packages/anthropic/_base_client.py", line 744, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'proxies'

```

Httpx deprecated proxies argument:
"
0.28.0 (28th November, 2024)
The 0.28 release includes a limited set of deprecations.

Deprecations:

We are working towards a simplified SSL configuration API.

For users of the standard verify=True or verify=False cases, or verify=<ssl_context> case this should require no changes. The following cases have been deprecated...

The verify argument as a string argument is now deprecated and will raise warnings.
The cert argument is now deprecated and will raise warnings.
Our revised [SSL documentation](https://github.com/encode/httpx/blob/master/docs/advanced/ssl.md) covers how to implement the same behaviour with a more constrained API.

The following changes are also included:

**The deprecated proxies argument has now been removed.**
The deprecated app argument has now been removed.
JSON request bodies use a compact representation. (#3363)
Review URL percent escape sets, based on WHATWG spec. (#3371, #3373)
Ensure certifi and httpcore are only imported if required. (#3377)
Treat socks5h as a valid proxy scheme. (#3178)
Cleanup Request() method signature in line with client.request() and httpx.request(). (#3378)
Bugfix: When passing params={}, always strictly update rather than merge with an existing querystring. (#3364)"

https://github.com/encode/httpx/blob/master/CHANGELOG.md

I believe this can be fixed by pinning httpx to a version less than 0.28.

**Comment by RobertCraigie** [comment]
This is fixed in the latest `anthropic` version, please try that.
