### ISSUE TITLE
Client.__init__() got an unexpected keyword argument ‘proxies’

### ISSUE THREAD

**Issue by WilliamWCYoung** [anthropics/anthropic-sdk-python#779]
Looks like this package is also effected by the `httpx` package changing a method signature:

https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332

We fixed this locally by doing the same as they suggest in the thread above:

```
httpx<0.28
```

**Comment by RobertCraigie** [comment]
This is already fixed in the latest version!

**Comment by nwyin** [comment]
Still seeing this error message on `anthropic==0.39.0` on Python 3.12.8

Downgrading to `http<0.28` fixes it.
