### ISSUE TITLE
PDF beta cannot see fields filled into editable PDFs

### ISSUE THREAD

**Issue by gordonhart** [anthropics/anthropic-sdk-python#780]
The beta PDF support (`pdfs-2024-09-25`) does not appear to be able to see values filled into editable PDF fields.

Minimal repro script `repro.py`:

```py
from base64 import b64encode

import anthropic

with open("sample.pdf", "rb") as f:
    pdf_block = dict(
        type="document",
        source=dict(
            type="base64",
            media_type="application/pdf",
            data=b64encode(f.read()).decode("utf-8"),
        )
    )

text_block = dict(type="text", text="what is the name provided?")
response = anthropic.Anthropic().beta.messages.create(
    messages=[dict(role="user", content=[pdf_block, text_block])],
    model="claude-3-5-sonnet-20241022",
    max_tokens=4096,
    betas=["pdfs-2024-09-25"],
)

print(response.content[0].text)
```

Running with this [sample.pdf](https://github.com/user-attachments/files/18081585/sample.pdf), the response indicates that Claude cannot see these values:

```
$ python3 repro.py
This is a blank sample fillable PDF form - there is no name filled in. The form shows an empty field for "Name" along with other empty fields like "Date" and "Address".
```

These fields are filled in on the PDF:

![Image](https://github.com/user-attachments/assets/7556b93f-8e95-4975-84ee-00116cab6a34)

Flattening this PDF for printing (to remove editability) fixes this issue, as does screenshotting the PDF and passing it in as an image.

Bug aside, PDF support is a great feature! Really simplifies my workflows. I hope it sticks around and gets promoted out of beta.

**Comment by michael-cohen-io** [comment]
Hey @gordonhart ! We've rolled out a fix for this issue and verified editable fields should now be getting read properly. Please let us know if you find any other issues with PDF support or if this doesn't work for you. Thank you for reporting this to us!

**Comment by gordonhart** [comment]
@michael-cohen-io, verified that it's fixed with the repro script. Awesome velocity guys, thanks for getting on this!
