### ISSUE TITLE
please remove jiter dependency

### ISSUE THREAD

**Issue by anarcat** [anthropics/anthropic-sdk-python#782]
Hi!

I'm looking at packaging this tool for debian, and we're missing the jiter package from debian. so I looked at packaging *that* but the [home page](https://pypi.org/project/jiter/) says:

> This is a standalone version of the JSON parser used in pydantic-core. The recommendation is to only use this package directly if you do not use pydantic.

Yet pydantic is already a dependency of this package, so why are we not using `from_json` from pydantic instead?

I mean I don't mind packaging yet another tiny Python library in debian, it's a thing, trust me, but I figured this sounded like technical debt on your end and it would be easier to fix by just changing the `import` here...

thank you for your consideration.

**Comment by RobertCraigie** [comment]
We have to use `jiter` because this package supports both Pydantic v1 and Pydantic v2. There is unfortunately no equivalent functionality available in Pydantic v1.

Unfortunately we also can't drop Pydantic v1 support anytime soon as it's still getting millions of downloads a day.

**Comment by anarcat** [comment]
understood... i'm wondering if you'd still be open to patches that make the dependency optional, that said?
