### ISSUE TITLE
'auth_token' not working

### ISSUE THREAD

**Issue by michaelchia** [anthropics/anthropic-sdk-python#85]
Problem:
'auth_token' parameter cannot be used even if 'api_key' is not set.
This is because in L87:
```
        api_key = api_key or os.environ.get("ANTHROPIC_API_KEY", "")
```
api_key is set to `""` by default instead of `None`.

Such that,
```
    @property
    def _api_key_header(self) -> dict[str, str]:
        api_key = self.api_key
        if api_key is None:
            return {}
        return {"X-Api-Key": api_key}
```
will return `{"X-Api-Key": ""}` instead of {} as expected.

Therefore,
```
    @property
    def auth_headers(self) -> dict[str, str]:
        if self._api_key_header:
            return self._api_key_header
        if self._auth_token_bearer:
            return self._auth_token_bearer
        return {}
```
will return `{"X-Api-Key": ""}` instead of `{"Authorization": f"Bearer {auth_token}"}` as expected.

https://github.com/anthropics/anthropic-sdk-python/blob/2a99183e0fc241a2502aff61723f518a095dc8d8/src/anthropic/_client.py#L87-L131

Solution:
change L87 to 
```
api_key = api_key or os.environ.get("ANTHROPIC_API_KEY", None)
```

**Comment by RobertCraigie** [comment]
Thanks for the bug report! We've pushed a [fix](https://github.com/anthropics/anthropic-sdk-python/pull/87/commits/9a3840d42aeeb5d917d376707e964babac869bfb) for this that will be included in the next release.

**Comment by rattrayalex** [comment]
https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.3.7 includes this fix.
