### ISSUE TITLE
ImportError: cannot import name 'Anthropic' from 'anthropic'

### ISSUE THREAD

**Issue by gwendolynr** [anthropics/anthropic-sdk-python#86]
Trying to run the basic code for Anthropic and getting this error: AttributeError: module 'anthropic' has no attribute 'Anthropic'
Using anthropic == 0.3.6
Code in my notebook: 

from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT

anthropic = Anthropic(
    # defaults to os.environ.get("ANTHROPIC_API_KEY")
    api_key='replaced with my actual api key',
)

completion = anthropic.completions.create(
    model="claude-2",
    max_tokens_to_sample=300,
    prompt=f"{HUMAN_PROMPT} how does a court case get to the Supreme Court? {AI_PROMPT}",
)
print(completion.completion)

**Comment by gwendolynr** [comment]
It works in a python shell but not in my anaconda jupyter notebook.

**Comment by rattrayalex** [comment]
We'd like to ensure this library works in anaconda jupyter notebooks, so I'll reopen this until we've been able to investigate. Can you share any more information about your setup?

**Comment by gwendolynr** [comment]
Ah well I discovered it was a package library conflict. I did a work around, but it might be worth looking into resolving since I'm fairly certain it's a conflict with the llama_index or langchain packages.

**Comment by l1n** [comment]
looks like you maybe imported * from `llama_index.llms`? Do you have a list of imports from that jupyter notebook?

**Comment by RobertCraigie** [comment]
Both `llama_index` & `langchain` are compatible with v0.3 of this library. Were you maybe using an older version?
